### ISSUE TITLE
Sync speed

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#1019]
![image](https://user-images.githubusercontent.com/22738317/81918922-6f895580-95d7-11ea-9049-c7f907f45ef4.png)

> Lighthouse can reach 100 block/s if enough peers and getting blocks served well, so it can do long-range BLS signature set optimization

**Comment by mratsim** [comment]
See update bench https://github.com/q9f/eth2-bench-2020-10

**Comment by arnetheduck** [comment]
https://github.com/byz-f/eth2-bench-mainnet - after the latest bls upgrades, most sync speed-related issues should be moot, specially considering that we should be moving over to a ws-centric sync experience some time soon
