### ISSUE TITLE
Requests not getting sent fully

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nimbus-eth2#1110]
`make witti` 

```
DBG 2020-06-03 17:48:32+02:00 Error processing request                   topics="networking" tid=1795609 file=eth2_network.nim:374 errMsg="Request full data not sent in time" peer=16Uiu2HAm1JrLAqWPcVcoQxKoRCe112cbNfwuFssPQyhzmG6URZPT responseCode=InvalidRequest
```

**Comment by cheatfate** [comment]
@arnetheduck this can be an issue when requests are not sent fully because of timeout or because remote peer is disconnected.

**Comment by arnetheduck** [comment]
this is an error that the remote peer sent us using the error message response in the rpc protocol (this message: https://github.com/status-im/nim-beacon-chain/pull/1109)

**Comment by arnetheduck** [comment]
Obsolete
