### ISSUE TITLE
suggest backup for validator private key

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nimbus-eth2#1115]
When the deposit helper is run, the private key for the generated validator gets written to a mostly hidden data directory - remind the user to back up this private key in a message! 

The manual should also describe this process in detail, and provide instructions to restore a backup.

```
Please enter your Goerli Eth1 private key in hex form (e.g. 0x1a2...f3c) in order to become a validator (you'll need access to 32 GoETH).
Hit Enter to skip this.
> ....
[NimScript] exec: /home/arnetheduck/status/nim-beacon-chain/build/beacon_node_shared_witti makeDeposits         --random-deposits=1         --deposits-dir="/home/arnetheduck/status/nim-beacon-chain/build/data/shared_witti/validators"         --deposit-private-key=0xD5CF8ED36B35071DF504746079445BDB4ED1145ECE414CB675B45341D6E77388         --web3-url=wss://goerli.infura.io/ws/v3/809a18497dd74102b5f37d25aae3c85a         --deposit-contract=0x42cc0FcEB02015F145105Cf6f19F90e9BEa76558         
INF 2020-06-04 09:57:56+02:00 Generating deposits                        tid=24829 file=validator_keygen.nim:28 outputDir=/home/arnetheduck/status/nim-beacon-chain/build/data/shared_witti/validators randomKeys=false totalValidators=0
INF 2020-06-04 09:57:56+02:00 Generating deposits                        tid=24829 file=validator_keygen.nim:28 outputDir=/home/arnetheduck/status/nim-beacon-chain/build/data/shared_witti/validators randomKeys=true totalValidators=1
INF 2020-06-04 09:57:57+02:00 Sending deposits                           topics="beacnde" tid=24829 file=beacon_node.nim:1014 depositContract=0x42cc0FcEB02015F145105Cf6f19F90e9BEa76558 web3=wss://goerli.infura.io/ws/v3/809a18497dd74102b5f37d25aae3c85a

Deposit sent, wait for confirmation then press enter to continue
```

somewhere close to Deposit sent, probably!

**Comment by arnetheduck** [comment]
for the record, the key gets written to `build/data/shared_witti/validators/v0000000.privkey` for `make witti` and must be restored there - as of bcbfa736c9501ab420615f4a6b2350d35727dac5 at least

**Comment by zah** [comment]
This is no longer valid with the Keystore workflow. I'll modify the onboarding flow to ask the user to remember the typical 12-word mnemonic that can be used to restore an account on a different computer.

The mnemonic controls the withdrawal credentials of the account. The "voting" key used for block proposals and attestations is derived in deterministic way from the withdrawal credentials and it remains persistently stored on the hard drive (as a keystore file and a separate password file used to unlock it). You can move these files to a new machine, but they are not enough to restore the withdrawal credentials.
