### ISSUE TITLE
Improve asynchronous exception stack traces.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nimbus-eth2#1118]
Because `libbacktrace` is unable to capture proper asynchronous stack traces we need to improve chronos stack traces.

#1113

**Comment by stefantalpalaru** [comment]
Fixed in https://github.com/nim-lang/Nim/pull/15284

Once that lands in a compiler we can use, this is how you can support it in Chronos (with backwards compatibility):

```diff
--- a/chronos/asyncfutures2.nim
+++ b/chronos/asyncfutures2.nim
@@ -397,7 +397,12 @@ proc getHint(entry: StackTraceEntry): string =
     if cmpIgnoreStyle(entry.filename, "asyncmacro.nim") == 0:
       return "Resumes an async procedure"
 
-proc `$`*(entries: seq[StackTraceEntry]): string =
+proc `$`(stackTraceEntries: seq[StackTraceEntry]): string =
+  when defined(nimStackTraceOverride) and declared(addDebuggingInfo):
+    let s = addDebuggingInfo(stackTraceEntries)
+  else:
+    let s = stackTraceEntries
+
   result = ""
   # Find longest filename & line number combo for alignment purposes.
   var longestLeft = 0
```

**Comment by cheatfate** [comment]
I think its time to stop manipulating that `libbacktrace` is able to improve "asynchronous" stack traces. This assumption is totally wrong, there no big difference in quality of stack traces obtained via `libbacktrace` and `nim`... The biggest problem not in the stacktrace, but in ability to store current stacktrace between different asynchronous calls.

**Comment by stefantalpalaru** [comment]
Done.
