### ISSUE TITLE
Deposit Transaction Gas Price is 1 Wei

### ISSUE THREAD

**Issue by q9f** [status-im/nimbus-eth2#1152]
Ohai!

The gas price for a deposit transaction is 1 Wei. Did you mean 1 GWei?

https://goerli.etherscan.io/tx/0xa839d0d6496668d9cbb3e7843f62227de04f79ac7a3e50d8db0fd22a3e94315d

**Comment by zah** [comment]
Since 1 Wei was OK for Goerli, we used that for testing purposes. It made it quite easy to recognise which deposits are made by us :)
