### ISSUE TITLE
Select a single WebSockets library for long-term usage

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#1219]
Currently, due to historic reasons, the project is using two separate WebSockets libraries:

1) https://github.com/Tormund/news (supports Chronos and AsyncDispatch)
2) https://github.com/niv/websocket.nim (supports AsyncDispatch only)

Both were integrated without passing an in-depth review. We should review the implementations and decide which one we would like to use and potentially maintain.

**Comment by zah** [comment]
It should be noted that even though news has some Chronos support, it current doesn't offer a way to create a WebSocket server using Chrons.

**Comment by kdeme** [comment]
Indeed, see also https://github.com/status-im/nim-json-rpc/issues/76#issuecomment-635892277

**Comment by jangko** [comment]
[nim-ws](https://github.com/status-im/nim-ws) is ready to replace both [news](https://github.com/status-im/news) and [websocket.nim](https://github.com/niv/websocket.nim)

see status-im/nim-json-rpc#103

**Comment by mratsim** [comment]
We use https://github.com/status-im/nim-websock

**Comment by zah** [comment]
We haven't yet integrated `nim-websock` in all projects due to concerns about its maturity, but I guess this issue can be closed since there is a plan in place.
