### ISSUE TITLE
loadTailState and CandidateChain.tail are unused

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#1243]
AFAIK they have no use at the moment since we should always use or load from the latest finalized head.

**Comment by arnetheduck** [comment]
the intent as I remember it was to advance the tail as we prune the database - in case we want to keep more history than the finalization point but less history than the entire history - ie typically we'd advance tail to the weak subjectivity point.

**Comment by mratsim** [comment]
I think that should be handled in the DB as a cache so that the DAG is kept minimal and only has what is needed to handle fork choice.

**Comment by arnetheduck** [comment]
`loadTailState` is gone, but `tail` needs to stay since it simple denotes where the chain ends (looking at the chain as a linked list) - initial code for weak subjectivity also uses it delimit where the horizon of our block tracking is
