### ISSUE TITLE
beacon_node::createWalletInteractively - the user provided password is not passed to `createWalletContent` -> wallets are not password protected

### ISSUE THREAD

**Issue by tintinweb** [status-im/nimbus-eth2#1319]
### Description

//just stumbled upon this while trying to get `beacon_node` to run.

`beacon_node wallets create` asks the user for a password that is never used. I assume the wallet is, therefore, set-up with an empty password (cannot test, see error below).

#### How to reproduce

create a wallet via the interactive console:

```
⇒  ./beacon_node --data-dir=./datadir wallets create
The created wallet will be protected with a password that applies only to the current Nimbus installation. In case you lose your wallet and you need to restore it on a different machine, you must use the following seed recovery phrase: 

unit cousin super wolf pudding canoe check emotion garment wasp suspect boat weasel potato walk wave bus grid core utility kite motor produce own
Please back up the seed phrase now to a safe location as if you are protecting a sensitive password. The seed phrase be used to withdrawl funds from your wallet.

Did you back up your seed recovery phrase? (please type 'yes' to continue or press enter to quit)
yes
When you perform operations with your wallet such as withdrawals and additional deposits, you'll be asked to enter a password. Please note that this password is local to the current Nimbus installation and can be changed at any time.
Please enter a password:
Please repeat the password:
For your convenience, the wallet can be identified with a name of your choice. Please enter a wallet name below or press ENTER to continue with a machine-generated name.

/Users/tintin/workspace/nim/nim-beacon-chain/vendor/nim-testutils/testutils/moduletests.nim(21) beacon_node
/Users/tintin/workspace/nim/nim-beacon-chain/beacon_chain/beacon_node.nim(1384) main
/Users/tintin/workspace/nim/nim-beacon-chain/beacon_chain/beacon_node.nim(1143) createWalletInteractively
/Users/tintin/workspace/nim/nim-beacon-chain/beacon_chain/conf.nim(469) walletsDir
/Users/tintin/workspace/nim/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: 'walletsDirFlag' is not accessible using discriminant 'cmd' of type 'BeaconNodeConf' [FieldError]

```

* password is read from stdin, checked against confirmedPassword but not passed to `createWalletContent`

https://github.com/status-im/nim-beacon-chain/blob/b0470d7318d05901d4cd6fd2fd635965480817c8/beacon_chain/beacon_node.nim#L1114-L1135

https://github.com/status-im/nim-beacon-chain/blob/b0470d7318d05901d4cd6fd2fd635965480817c8/beacon_chain/spec/keystore.nim#L435-L446

### Recommendation

* pass user provided password to `createWalletContent`
* The application should also enforce a minimum password strength / implement a password blacklist for common passwords / and/or provide a password strength indicator

**Comment by zah** [comment]
Thanks for spotting this. 

The truth is that the `wallets create` command was in development and was not finished in time due a shift in priorities related to the Altona testnet launch. I've now completed the implementation in the PR referenced above. 

The PR significantly improves the user experience, adds a minimum password length of 10 characters and uses the following list of 100000 commonly used passwords:

https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-100000.txt

**Comment by tintinweb** [comment]
LGTM #87955f2d37c7b7e8b9f8ae1c47c9d354c59a1c34
- password strength enforced
- walletfile rw by owner only
- wallet encrypted
