### ISSUE TITLE
Connection with bootstrap nodes.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nimbus-eth2#1370]
We all can agree that bootstrap nodes are important for P2P network. Using bootstrap nodes discovery5 can obtain list of peers registered in network. But is it so important to have libp2p connection with bootstrap node?

For example if all the clients will start querying data from bootstrap node? How many clients Ethereum1 has, we can expect same amount of clients for Ethereum2, and all this clients will query bootstrap node for blockchain data. Is it good scenario? i dont think so, because keeping such bootstrap node for a while could cost too much money. While keeping bootstrap nodes which only supports discovery5 service is much more cheaper.

In our current code we are warning user that we are unable to connect to bootstrap node (actually this code is incorrect and if you get new connection with some other peer it will stop warning), but if for some weird reason you will be unable to establish any outgoing connection, while incoming connections will be accepted, this warning will still be shown.

Proposition:
1) Remove process of connection to bootstrap node via `libp2p`.
2) Treat bootstrap nodes as regular nodes, if this nodes will be returned by `discovery5` attempt to connect to this nodes.
3) Continuously monitor and warn user if there no libp2p connections at all.

**Comment by arnetheduck** [comment]
This is the current behavior - bootstrap nodes are only used for libp2p when discovery is disabled: https://github.com/status-im/nimbus-eth2/blob/254e0fe2e215f4ea5a038120cda09961e5270a78/beacon_chain/networking/eth2_network.nim#L1456:L1456
