### ISSUE TITLE
Update inspector tool to gossip 1.0 / 1.1

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nimbus-eth2#1495]
`inspector` should work flawlessly as it avoids many of the distractions of a full nbc node:

* selective gossip topic subscription
* no main thread hogging

**Comment by dryajov** [comment]
I would add an option to enable metrics as well.

**Comment by cheatfate** [comment]
Its impossible to run `inspector` in gossip 1.1 network, because if we will going to be silent for some amount of time we will be penalized and kicked at some moment. To survive 1.1 we need rebroadcasting at least.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/2737 removed the inspector tool entirely due to this.
