### ISSUE TITLE
Windows builds still requires CMake.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nimbus-eth2#1528]
We have problems when people trying to run
```mingw32-make test```

This should not be happened because CMake dependency was set only to compile `libbacktrace` which is not used on Windows anymore.

**Comment by stefantalpalaru** [comment]
You didn't disable it properly, when you were hiding that stack corruption under the rug: https://github.com/status-im/nim-beacon-chain/blob/9244ae7a3867c3158130304901169fa685b3aaff/Makefile#L91-L96

**Comment by cheatfate** [comment]
Please stop spreading your unproven claims. What we saw many times with `libbacktrace/libunwind` that it unable to properly unwind stack (e.g. stop at right place/moment) and causes crashes inside of its own loop, in pretty simple scenarios/examples of just calling `getStackTrace()`. And this was reproduced not only by me.

**Comment by mratsim** [comment]
Now we need libbacktrace again: #3453 and #3466
