### ISSUE TITLE
More efficient state storage

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nimbus-eth2#1627]
Currently, the BeaconState object is saved fully for every epoch which is slow.

Looking at the BeaconState object, once can broadly categorize them as follows:

* statically bounded per-epoch lists-of-things - `block_roots`, `state_roots` etc - these are updating using a circular / modulo slot index - `HashArray` in the code
* dynamic lists - validator set, attestations, eth1 votes
  * validators are interesting in particular because the bulk of the data (key) is static
* leftovers - these are small, statically sized items

It could thus make sense to write 3-4 records per state per epoch:

* statically bounded items in an append-only structure, such that ranges can be queried - this would allow reconstructing any range of data and pluck it into the circular list
* validator statics - key, withdrawal credentials, additive list
* dynamic lists - other validator information in full (balances, effective balances, etc)
* leftovers + small dynamic lists (eth1, attestations) - in particular, after epoch processing, `current_epoch_attestations` for example is always empty, and eth1 votes are emptied every `EPOCHS_PER_ETH1_VOTING_PERIOD` epochs

Downside would be that state must be collected from multiple sources, upside would be more efficient long-term storage.

This kind of storage would be suitable for finalized states.

For unfinalized states, a state-diff object could be constructed as well outlining differences against the finalized state only (in particular, it would avoid reserializing the validator set) - this way, finalized state would be kept in cache and diff would be applied for example to validate attestations

**Comment by stefantalpalaru** [comment]
Our 6 AWS Medalla nodes ran out of disk space on their 150 GiB partitions.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/2297 does some of this.

**Comment by mratsim** [comment]
The state is a bottleneck on prune https://github.com/status-im/nimbus-eth2/issues/2440

**Comment by tersec** [comment]
Howso? Deleting a small state should take similar time as deleting a large state.

**Comment by mratsim** [comment]
Closing this, we had numerous improvements since then:

- faster state loading: https://github.com/status-im/nimbus-eth2/pull/3164
- new DB schema: https://github.com/status-im/nimbus-eth2/pull/2560
- 4x reduction is state storage frequencies: https://github.com/status-im/nimbus-eth2/pull/2542
- Planned era files for long-term: https://github.com/status-im/nimbus-eth2/pull/2382

If more is needed, new issues with quantifiable goals to avoid "always open issue creep"
