### ISSUE TITLE
Sync v2 legend in the prompt

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#1640]
From Discord, the sync v2 string is not possible too parse for users at the moment.

We need to add the legend from #1602 to the prompt

```
StatusBar

<sync worker map>:<number of actively working workers>:<current syncing speed in blocks/second>

legend:

    s - sleeping (idle),
    w - waiting for a peer from PeerPool,
    R - requesting blocks from peer
    D - downloading blocks from peer
    P processing/verifying blocks
    U updating peer's status information
```

**Comment by arnetheduck** [comment]
>  to the prompt

manual you mean?

**Comment by mratsim** [comment]
prompt, people running the node though it was gibberish even our own Status devs (from other teams).

**Comment by sachayves** [comment]
suggest replacing `<number of actively working workers>` with `<number of active workers>`

**Comment by mratsim** [comment]
I don't remember the syncing display at the time, but since the launch we didn't get user feedback that it was hard to read anymore, hence considering it solved.
Furthermore most are using systemd/service and not CLI.

![image](https://user-images.githubusercontent.com/22738317/157422271-82229df0-b867-4ab9-9678-338e952c04ab.png)
