### ISSUE TITLE
Sync get stucked at a random block

### ISSUE THREAD

**Issue by diglos** [status-im/nimbus-eth2#1647]
This is the third attempt of syncing Medalla with the same result, at a certain point (before reaching 1.000 slots) the sync gets stuck at a block and do not move forward.

1. Raspberry Pi 4 Ubuntu 64 20.04.1
2. Nimbus beacon node v0.5.0 (c76305f8)
Copyright (c) 2019-2020 Status Research & Development GmbH

eth2 specification v0.12.2

Nim Compiler Version 1.2.6 [Linux: arm64]
Compiled at 2020-09-14
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: bf320ed172f74f60fd274338e82bdc9ce3520dd9
active boot switches: -d:release

3. beacon_node --network=medalla --data-dir=/home/ethereum/.nimbus --web3-url=http://localhost:8545 --tcp-port=19000 --udp-port=19000 --log-level=info --log-file=/home/ethereum/.nimbus/nimbus.log --metrics (as a systemd service)
4. Find log attached

[nimbus.log](https://github.com/status-im/nim-beacon-chain/files/5223151/nimbus.log)

**Comment by diglos** [comment]
Hi,

find below another log stucked on 104 headSlot after 2 hours syncing:

[nimbus.log](https://github.com/status-im/nim-beacon-chain/files/5224098/nimbus.log)

This warning is really odd (happens in every sync):

{"lvl":"WRN","ts":"2020-09-15 07:50:36.886+00:00","msg":**"Unexpected missing parent, rewind happens**","topics":"beacnde","tid":684452,"file":"sync_manager.nim:484","peer":"16*rDe9jp","rewind_to_slot":0,"request_slot":128,"request_count":32,"request_step":1,"blocks_count":7,"blocks_map":"xx.xx.xx.x......................"}

**Comment by diglos** [comment]
Hi,
Just tried the commit b3a9afa but it doesn't fix the problem. Attached find another log in debug mode (see slot 671).
[beacon_node-nimbus-20200925.log](https://github.com/status-im/nim-beacon-chain/files/5284555/beacon_node-nimbus-20200925.log)

**Comment by arnetheduck** [comment]
@diglos I just checked beacon_node-nimbus-20200925.log the log and it appears you're still on version 6cf7e837 which is missing a couple of important fixes - can you try latest master?

**Comment by diglos** [comment]
Hi, I just did and same result:

WRN 2020-09-30 08:07:26.010+00:00 Unexpected missing parent, rewind happens  topics="beacnde" tid=1275712 file=sync_manager.nim:489 peer=16*brfvSG rewind_to_slot=0 request_slot=320 request_count=32 request_step=1 blocks_count=23 blocks_map=xx.xxxx.x.xx.x.x.xxxxxxxxx..xx.x

And back to a stucked sync. Any hint of what is going on?

Thanks!

**Comment by sachayves** [comment]
@diglos can you try again on latest master?

I've tried reproducing (without an attached validator) with a raspberry pi 4 and no luck.

I ran both

```
make medalla`

and

```
beacon_node --network=medalla  --tcp-port=19000 --udp-port=19000 --log-level=info
```

Synced the first 2,000 blocks without a problem.

**Comment by diglos** [comment]
Attached find another log in debug mode according to this discussion:

https://twitter.com/ssaintleger/status/1318612058175344642

[nimbus-20201021.log.zip](https://github.com/status-im/nimbus-eth2/files/5421318/nimbus-20201021.log.zip)

**Comment by arnetheduck** [comment]
Fixed! https://twitter.com/EthereumOnARM/status/1321850920574046208

**Comment by diglos** [comment]
Hi,

As mentioned on Twitter last Friday, it seems that a fresh sync does fine but when you stop and resume the sync (or it gets interrupted by a network problem) it goes really slow. Ffind attached a log where you can see the sync progress and howt it gets often stuck in a block and take a long time to resume the sync.

[nimbus-log.log.zip](https://github.com/status-im/nimbus-eth2/files/5506847/nimbus-log.log.zip)
