### ISSUE TITLE
[SEC] Crash in `deposits create`

### ISSUE THREAD

**Issue by shayanb** [status-im/nimbus-eth2#1683]
**Describe the bug**
When creating a wallet using `./beacon_node deposits create`, user faces a crash stack trace.

**To Reproduce**
1. Platform details (OS, architecture): macOS 10.15.6 
2. Branch/commit used: nbc-audit-2020-2
3. Commands being executed: `./beacon_node deposits create`
4. Relevant log lines:
```
Please enter a password:
Please repeat the password:

For your convenience, the wallet can be identified with a name of your choice.
Please enter a wallet name below or press ENTER to continue with a
machine-generated name.
Wallet name: nimbus_test
/Users/sbeta/Documents/Consensys/Github/nim-beacon-chain/vendor/nim-testutils/testutils/moduletests.nim(21) beacon_node
/Users/sbeta/Documents/Consensys/Github/nim-beacon-chain/beacon_chain/beacon_node.nim(1247) main
/Users/sbeta/Documents/Consensys/Github/nim-beacon-chain/beacon_chain/keystore_management.nim(448) createWalletInteractively
/Users/sbeta/Documents/Consensys/Github/nim-beacon-chain/beacon_chain/keystore_management.nim(380) pickPasswordAndSaveWallet
/Users/sbeta/Documents/Consensys/Github/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: 'walletsCmd' is not accessible using discriminant 'cmd' of type 'BeaconNodeConf' [FieldError]
```

**Comment by zah** [comment]
Fixed in b6262bfe46d4b29939a35ffec24e0c0b83c84679

**Comment by tintinweb** [comment]
(review: 1994ffe5a0454c0395c4c216b8368434676defaa) 

- ✗ overwrites existing wallet file without notifying the user (pot. key-loss) (reprod: create new wallet with name `nimbus_test` twice)
- ✓ no more crash

**Comment by zah** [comment]
There have been additional fixes related to this issue in the [misc-fixes branch](https://github.com/status-im/nimbus-eth2/pull/1851) which is now merged in devel. The latest version of the code directly refuses to overwrite an existing wallet:

```bash
[Nimbus env] ➜  nim-beacon-chain git:(devel) ✗ ls "/Users/zahary/Library/Application Support/Nimbus/BeaconNode/wallets/"
nimbus_team.json
[Nimbus env] ➜  nim-beacon-chain git:(devel) ✗ build/beacon_node wallets create --name:nimbus_team
The Wallet 'nimbus_team' already exists.
```
