### ISSUE TITLE
[SEC] CLI - Refactor seed recovery phrase word flow

### ISSUE THREAD

**Issue by shayanb** [status-im/nimbus-eth2#1689]
# Description
When creating a new wallet using the CLI, it is suggested to:
- Inform the user the mnemonic will be shown to make sure they are alone and secure before showing the seed phrase on the screen
- Ask the used to back up the seed phrase and press Enter
- Clear the terminal screen (simply to prevent over the shoulder snooping) 
- Prompt and ask for the a few of the words (e.g. The first 2 and the last 2)
- Remind the user to clear their clipboard if they have copied the seed (very lilkely)

Currently it pops the seed phrase and prompts the user to type `yes` which is redundant. 

```
➜ 🍺  build (nbc-audit-2020-2) ./beacon_node deposits create
The generated wallet is uniquely identified by a seed phrase consisting of 24
words. In case you lose your wallet and you need to restore it on a different
machine, you must use the words displayed below:

nephew mansion frown window such acid strategy now one dash sauce melt cash
scrap wing citizen gain else pill install domain detail supreme wealth

Please back up the seed phrase now to a safe location as if you are protecting a
sensitive password. The seed phrase can be used to withdrawl funds from your
wallet.

Did you back up your seed recovery phrase?
(please type 'yes' to continue or press enter to quit)
Answer: yes
```

**Comment by tintinweb** [comment]
LGTM

reviewed as part of https://github.com/status-im/nimbus-eth2/issues/1319#issuecomment-765326999
