### ISSUE TITLE
Windows 32-bit finalization test - Illegal Storage after writing deposits

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#1725]
![image](https://user-images.githubusercontent.com/22738317/93869603-50f54280-fccc-11ea-9685-aecfa73d1083.png)

Relevant branch and part of the code

https://github.com/status-im/nim-beacon-chain/blob/d35b16076204ecb60fc5c1016b38a2b23d205062/beacon_chain/beacon_node.nim#L1166-L1171

PR: https://github.com/status-im/nim-beacon-chain/pull/1693

**Comment by arnetheduck** [comment]
We're no longer testing / supporting windows 32-bit
