### ISSUE TITLE
slow initial db state load

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nimbus-eth2#1730]
More visible on HDDs, after clearing fs caches as root: `echo 3 > /proc/sys/vm/drop_caches`

A wall-clock profile shows it's just SQLite reading stuff (for approx. 2.5 minutes on a db with 1100 epochs worth of Medalla data in it):

![profile_19_120.svg](https://gist.githubusercontent.com/stefantalpalaru/3bb561a82ab9d95363e10e2685af9b36/raw/228613015bf0d608ee629bbaf6b0b4c2008599e7/profile_19_120.svg)

**Comment by tersec** [comment]
Apparently to verify the database integrity (?), it does a complete walk from chain DAG head to tail, even though it doesn't need to venture beyond the finalized epoch:
https://github.com/status-im/nim-beacon-chain/blob/2bc26940d4ce5ea9f824cd986c7f185817dcc1b2/beacon_chain/block_pools/chain_dag.nim#L307-L330

**Comment by arnetheduck** [comment]
@tersec it's more to build the `blocks` table so lookups for older blocks work

**Comment by stefantalpalaru** [comment]
Another flame graph obtained with `perf record --call-graph dwarf,16000 -e task-clock -p $(pidof beacon_node)`:

![perf.svg](https://gist.githubusercontent.com/stefantalpalaru/98a9641ca43a16af3795e28a8e1b9fc6/raw/0e834e25fb86d8738d9afdd0556892171468ca22/perf.svg)

**Comment by arnetheduck** [comment]
this gets mitigated by #1950
