### ISSUE TITLE
Integration tests (local_testnet) in Github Actions

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#1737]
Github Actions provides us enough speed and parallel jobs to make integration tests via launch_local_testnet.sh viable.
In particular a `minima` config is fast enough to run within the timespan of unit tests.

This would also allow us to only test mainnet in Jenkins instead of both minimal+mainnet saving about 15~20 min of time.

Note, the script EXECUTOR_NUMBER would have to be fixed, see comment: https://github.com/status-im/nim-beacon-chain/pull/1693#discussion_r494243070

**Comment by zah** [comment]
Implemented long time ago.
