### ISSUE TITLE
Enhancement request: Fully support static binary in a scratch container

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nimbus-eth2#1765]
- Nimbus beacon node v0.5.0 (da3102c0)
- Nimbus compiled with `make NIMFLAGS="--passL:-static" beacon_node` inside buster-slim
- Dockerized environment, "scratch" container
- beacon_node configured for testnet spadina

Low, low priority. This may be more a documentation issue than anything else. Possibly compiling inside alpine with musl
instead of buster with glibc would already do the trick.

Warnings during compilation:

```
<artificial>:(.text+0x1bbd9): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
connecthostport.c:(.text+0x154): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Error when running in scratch container:

```
ERR 2020-09-27 06:05:35.498+00:00 Failed to initialize Eth1 data provider    tid=1 file=mainchain_monitor.nim:753 provider=web3(http://geth:8545)
```

Running the very same static-compiled exe in buster-slim:

```
beacon_1            | INF 2020-09-27 06:08:27.916+00:00 Starting Eth1 deposit contract monitoring  tid=1 file=mainchain_monitor.nim:758 contract=0x07b39f4fde4a38bace212b546dac87c58dfe3fdc url=web3(http://geth:8545)
```

**Comment by stefantalpalaru** [comment]
Not really something we can fix, since it's at the Glibc level.

The best strategy is to run the software in a Docker image with a compatible Glibc version and to dynamically link it, like we do when we generate the distributable binaries and official Docker images.
