### ISSUE TITLE
Beacon cannot communicate with geth over http://

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nimbus-eth2#1767]
- Nimbus beacon node v0.5.0 (da3102c0)
- Dockerized environment, buster-slim
- Local geth accessed via http://geth:8546
- geth configured for --http.api eth,net
- beacon_node configured for testnet spadina

Beacon shows an error, "notifications not supported". Asking in Discord, suggested workaround was to use ws:// instead for geth.

```
{"lvl":"INF","ts":"2020-09-28 11:19:08.807+00:00","msg":"Starting Eth1 deposit contract monitoring","tid":1,"file":"mainchain_monitor.nim:758","contract":"0x48b597f4b53c21b48ad95c7256b49d1779bd5890","url":"web3(http://geth:8545)"}
{"lvl":"INF","ts":"2020-09-28 11:19:08.808+00:00","msg":"Waiting for new Eth1 block headers","tid":1,"file":"mainchain_monitor.nim:415"}
{"lvl":"ERR","ts":"2020-09-28 11:19:08.812+00:00","msg":"Mainchain monitor failure, restarting","tid":1,"file":"mainchain_monitor.nim:796","err":"{\"code\":-32000,\"message\":\"notifications not supported\"}"}
```

Suggested behavior: beacon_node can connect to local geth node over http:// API

This may be an enhancement request or a bug, depending on whether http:// is expected to be functional today

**Comment by mratsim** [comment]
We will have to check if Geth proposes a more secure API as as a general remark auditors recommended not to use unauthenticated connection to prevent man-in-the-middle attacks: https://github.com/status-im/nim-beacon-chain/issues/1665

That said we can always gate that feature behind `-d:insecure` flag.

**Comment by zah** [comment]
Using HTTP(S)-based web3 providers is not supported yet, due to lack of suitable client libraries compatible with our networking stack. We plan to address this in the future, but for now please use web-socket end points. Both `ws://` and `wss://` are supported.

**Comment by mratsim** [comment]
We now support https endpoints: https://github.com/status-im/nimbus-eth2/releases/tag/v1.7.0
