### ISSUE TITLE
Beacon quits if eth1 source is not fully up yet

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nimbus-eth2#1768]
- Nimbus beacon node v0.5.0 (da3102c0)
- Dockerized environment, buster-slim
- Local geth accessed via ws://geth:8546
- beacon service depends_on geth service

Docker does not support waiting for a port to be up without external tooling. As a result, although geth starts before beacon_node, beacon_node can fail, depending on timing, because it cannot connect to geth quite yet:

```
beacon_1            | libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
beacon_1            | Traceback (most recent call last, using override)
beacon_1            | Error: unhandled exception: (111) Connection refused [TransportOsError]
```

Suggested change: beacon_node does not quit when it can't find its eth1 source, it keeps trying to connect to it instead.

This may be an enhancement or a bug report, depending on whether you expect beacon_node to already survive the eth1 source not being "up" yet.

**Comment by zah** [comment]
We considered this a feature and implemented continuous polling until the Eth1 client is appropriately synced.
