### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by unixpi** [status-im/nimbus-eth2#1793]
A user config file that supports:

- loglevel
- network
- infura endpoint
- ports

What else?

Ideally, would be automagically fetched when you run `make medalla`.

Otherwise

```
make medalla --config=myfile.config
```

Same for beacon node (needs to be done before we start recommending running the beacon node manually imo).

**Comment by zah** [comment]
@jangko and I will work on integrating his work on TOML files in Confutils and this will give us a full-fledged config system.

**Comment by sachayves** [comment]
Great :)

**Comment by mratsim** [comment]
Added in https://github.com/status-im/nimbus-eth2/pull/3442

Do we need docs or further polish for this to be usable by users?

**Comment by mratsim** [comment]
Fixed by https://github.com/status-im/nimbus-eth2/pull/3475
