### ISSUE TITLE
Disable stdout logging

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nimbus-eth2#1794]
When running the node as a systemd service with json logging enabled, the stdout logging uses valuable cycles and is unnecessary - add a way to disable it.

**Comment by zah** [comment]
It's usually recommended to log to stdout under systemd. This would allow systemd to take care of log rotation and archival for you (and it will consider policies set by the system administrator). In my opinion, we need options for controlling the log format on stdout (this would include an option to disable it). The logging to file can remain optional and to make it more practical, we need to add a custom signal handling for log rotation events.

**Comment by arnetheduck** [comment]
sgtm as long as format can be chosen

**Comment by elitedev1314520** [comment]
I would like to help with fixing issues.
Is there anyone I can chat with for this?

**Comment by zah** [comment]
@elitedev1314520, sure! Come join our Discord (https://discord.gg/XRxWahP) and message me there (zahary).
