### ISSUE TITLE
Warning on long inclusion distance

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#1809]
From https://discordapp.com/channels/613988663034118151/616299964242460682/761949080531894282

It would be nice to give warnings when a validator's attestations have a long inclusion distance.

We've had (random?) period of bad network or peer quality or DoS on Spadina

Validator 1
![image](https://user-images.githubusercontent.com/22738317/95067555-5018d380-0704-11eb-9b6b-42a83d7e0815.png)

Validator 2
![image](https://user-images.githubusercontent.com/22738317/95067828-a9810280-0704-11eb-977b-fe81488a86f0.png)

This is very visible in the income graphs with income "blips":
![image](https://user-images.githubusercontent.com/22738317/95067882-c1f11d00-0704-11eb-870a-77d436c775d7.png)

![image](https://user-images.githubusercontent.com/22738317/95067938-d46b5680-0704-11eb-93da-3a84f0d9b3d5.png)

**Comment by arnetheduck** [comment]
#2925
