### ISSUE TITLE
Node out of sync, skipping validator duties

### ISSUE THREAD

**Issue by lufa23** [status-im/nimbus-eth2#1815]
After launching ` make medalla`, the node seems not to be able to sync, getting stucked at the same epoch.

I would like to monitor the node and get some data, so my priority is to run it as a client more than a validator.
Eitherway, i thought that the node would sync automatically.

How can i make it sync?

Thanks
![Screenshot 2020-10-06 at 11 12 44](https://user-images.githubusercontent.com/67415638/95182672-34c1cd00-07c5-11eb-9605-f583fdc8b6b8.png)

**Comment by mratsim** [comment]
It seems like you are connected to 0 peers, there will be a warning in the future for that. 

Regarding the loss of peers, I have a couple of questions:
1. Are you behind a firewall?
2. Does it work if you restart?
3. Can you restart with `make LOG_LEVEL=DEBUG medalla` for 5 min and send us the logs (you can attach them the issue or use a pastebin service). I recommend removing your IP address if it appears.

**Comment by lufa23** [comment]
Here the logs:

![Screenshot 2020-10-06 at 11 53 48](https://user-images.githubusercontent.com/67415638/95186794-aa7c6780-07ca-11eb-9978-475a1a6f7722.png)

What do you suggest in order to have the node gathering data and run just as a client?

**Comment by mratsim** [comment]
`make medalla` is enough.

It seems like there is a process (the other beacon_node?) already using the port in this screenshot and that that second error is different from the first one.

By default the beacon node uses port 9000 and you can check with
`lsof -i :9000` if any processes is using it before hand.
If there are any, you can change the port to 9100 (for example) with
```
make NODE_PARAMS="--tcp-port=9100 --udp-port=9100" medalla
```

**Comment by lufa23** [comment]
Great, thanks. yes there was another beacon node running on that port. I killed the process and "make medalla" to run it again.

**Comment by mratsim** [comment]
@kdeme is looking into the bootstrap node

**Comment by lufa23** [comment]
i tried to launch logged from another Wifi and it worked, so i guess it's a problem of IP / Firewalls.
Which network configuration are needed in order to run successfully the Nimbus node?
Thanks
