### ISSUE TITLE
Add sync status to slot start/slot end

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#1817]
Add sync status to slot start/slot end

### Rationale
Users may not always have the beacon node running in a CLI but as a systemd service.

It would also be helpful to debug issues to find sudden desync.

**Comment by arnetheduck** [comment]
maybe to the skipping validator duties as well - ie the message is a bit depressing, "out of sync" - better would probably be "syncing in progress" if it is in progress, or something to this effect

**Comment by cheatfate** [comment]
@mratsim @arnetheduck what you mean under term "sync status" is it current syncing slot/block, or its value in percents?

**Comment by arnetheduck** [comment]
I think the same info as in the status bar (synced or the sync string with peers)

**Comment by arnetheduck** [comment]
included in https://github.com/status-im/nimbus-eth2/pull/2195
