### ISSUE TITLE
Introduce a `make benchmark` target

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#1828]
A Makefile target can lower the knowledge required from core and external contributors to setup and execute the benchmarks, thus making them more accessible. 

Separate targets can be created for the individual benchmarks and a single `make benchmark` target can run all of them together. Ideally, all benchmarks should produce machine readable results in files and a useful print out on the screen.

To simplify things and to increase the consistently of the results, the benchmark execution scripts may download and cache the data files required for the benchmarks from Status infrastructure servers or S3 (e.g. a medalla database).

**Comment by arnetheduck** [comment]
Initial list of relevant benchmarks:

* `ncli_db bench` on medalla sqlite database with 10000 blocks 
* `block_sim` with mainnet settings and 50k validators (genesis is slow to generate but can be cached)
