### ISSUE TITLE
Nimbus should join the public Eth2 attacknets

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#1831]
Once our security audit is over, Nimbus should join all the public Eth2 attacknets:
https://github.com/ethereum/public-attacknets

This would require setting up corresponding Makefile targets and configs and setting up a cluster of permanently connected Nimbus nodes.

**Comment by arnetheduck** [comment]
Attack net program is down, there's a replacement bounty program that we should now be ready for, post-audit
