### ISSUE TITLE
`beacon_node deposits import ...` should silently skip "deposit_data-*.json"

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nimbus-eth2#1838]
Instead of trying to import it as a keystore and loudly failing with:

`WRN 2020-10-08 00:39:20.694+02:00 Invalid keystore                           tid=18257 file=keystore_management.nim:491 err="/src/77_DLD/CODE/status/eth2.0-deposit-cli/validator_keys/deposit_data-1602109932.json(1, 0) Unexpected token 'tkBracketLe' in place of 'object start bracket'"`

**Comment by sachayves** [comment]
perfect :)
