### ISSUE TITLE
Time left until synced

### ISSUE THREAD

**Issue by sachayves** [status-im/nimbus-eth2#1927]
Provide an estimate of the time left until synced.

**Is your feature request related to a problem? Please describe.**
As it stands, there's a syncing footer that keeps you updated on your syncing status. `sync` tells you how fast you're syncing (in blocks per second), and how many blocks you've synced so far. But what you really care about is how long until you're synced. As it stands you need to work this out yourself. While not terribly complicated, it is a little bit of a nuisance.

**Describe the solution you'd like**
An addition to the footer that gives you an estimate of how long left until you've synced to the head of the chain, based on your current sync speed and progress so far.

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by tersec** [comment]
When the chain's not finalizing and there are enough heads alive, I haven't seen that it takes any easily predicted/deterministic amount of time to begin with, which is Medalla's current state.

**Comment by sachayves** [comment]
@tersec right. I don't think it has to be terribly accurate under all situations to be useful though.

**Comment by tersec** [comment]
It's possible for it to be bad enough to be literally a punchline: https://xkcd.com/612/

I'd just be wary of something which provided excessive false confidence.

**Comment by sachayves** [comment]
Presumably, that risk only really exists during long periods of non-finality?

We could add a clarification somewhere : e.g. assuming the chain is finalising correctly ?

**Comment by tersec** [comment]
Yes, it should be reasonably reliable during finality. The disclaimer you propose would be reasonable, though it requires understanding of the idea of finality/non-finality.

**Comment by sachayves** [comment]
I think we can safely assume validators understand the risks associated with an inactivity leak: and therefore with non-finality (we can think about how to word it in a jargon-free way).

**Comment by sachayves** [comment]
@tersec What if we displayed percentage synced instead?

**Comment by tersec** [comment]
@sachayves Sounds good to me, but it'd a bit of an odd metric, in terms of defining the base. It can't be the genesis block, especially as mainnet will grow to tens or hundreds of thousands of epoch. It could remember when it first started syncing, so if it's from epoch X to epoch Y, it's (current-X)/(Y-X) * 100% through.

**Comment by arnetheduck** [comment]
@tersec we always have a starting point that we can use, be it genesis or weak subjectivity horizon - ultimately it'll depend on pruning mode

**Comment by tersec** [comment]
@arnetheduck sure, it's just that if if one's syncing from epoch 10,290 to 10,999, it's absurd to just lump the whole process in as 99%.

**Comment by arnetheduck** [comment]
I dunno - sounds reasonable to me - ie I start the thing, it syncs 50% and I restart it - it should pick up from 50%, naturally.. (or 49% probably since the chain moved on)

**Comment by arnetheduck** [comment]
right now, we show head vs wall clock - this is how you know if you're synced or not, really - when they're "close" you're good.. another thing we can have is simply a manual page that explains what to look for and what is "normal" - even with a percentage, we should probably have that - eventually, that can be translated into an automated health indicator (green/yellow/red or whatever)
