### ISSUE TITLE
eth2 networking warning log

### ISSUE THREAD

**Issue by sachayves** [status-im/nimbus-eth2#1931]
**Is your feature request related to a problem? Please describe.**
When eth2 networking receives a bunch of nodes from discovery, but no new "good" nodes are available, and the target amount of peers (25% of 79) has not been reached, nimbus logs the following message:

```
WRN Less than 25% wanted peers and could not discover new nodes
```

I don't think the log does a good job at being self-explanatory. In fact, it's quite anxiety inducing. For example, it's not clear you'll ever be able to discover new nodes... The term `wanted peers` is also confusing.

**Describe the solution you'd like**

```
WRN
Connected to less than 25% of target peers and no new nodes received
```

**Describe alternatives you've considered**
Open to alternative suggestions! @kdeme

**Comment by cheatfate** [comment]
Because this log is introduced by @mratsim i think its also important to hear his notes.

**Comment by zah** [comment]
Addressed in https://github.com/status-im/nimbus-eth2/pull/2114
