### ISSUE TITLE
Hide scary warning messages on startup

### ISSUE THREAD

**Issue by unixpi** [status-im/nimbus-eth2#1937]
**Is your feature request related to a problem? Please describe.**
As it stands, the first thing a user is bombarded with are  various  warning messages, before hanging on:

```
Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]
ld: warning: could not create compact unwind for _blst_sha256_block_data_order: does not use RBP or RSP based frame
```

This is not particularly reassuring, and doesn't give a good first impression.

**Describe the solution you'd like**
Hide both warning messages from the user by default.

**Relevant links**
 https://github.com/status-im/nimbus-eth2/issues/1634#issuecomment-691663458

**Comment by zah** [comment]
Fixed quite some time ago.
