### ISSUE TITLE
Email list to inform users of critical issues/updates

### ISSUE THREAD

**Issue by dankrad** [status-im/nimbus-eth2#1946]
When critical updates are published, or there are urgent problems with the clients that need all stakers to intervene, there should be a way to quickly get this information out to all Nimbus users. I recommend:
 *  Setting up an email list that stakers can subscribe to and on which highly critical information can be pushed
 * Additionally, setting up groups/accounts on other channels (twitter, telegram, etc.) can be helpful

Not all users can be expected to constantly monitor discussion channels such as discord, so having a low-noise direct channel that reliably reaches all stakers is essential.

**Comment by sachayves** [comment]
Twitter is already covered, so perhaps an email list + Status group/channel ? Thoughts?

**Comment by dankrad** [comment]
Sorry for posting on the wrong repo :)
I'd say that an email list is essential.

**Comment by dankrad** [comment]
Are you guys still doing this? Would be nice to have the list ready before launch.

**Comment by ZaneCEO** [comment]
I subscribed to this GitHub for new releases and I receive a nice email every time. Maybe this is enough and doesn't put additional burden on the team.

**Comment by mratsim** [comment]
The mailing list is a high priority for us and we are currently testing either:
- Mailtrain: https://github.com/Mailtrain-org/mailtrain which has the nice benefits of alowing encrypted mail for subscriber who wants to
- Listmonk: https://github.com/knadh/listmonk

**Comment by unixpi** [comment]
Addressed here:
https://subscribe.nimbus.team
