### ISSUE TITLE
Resource issue with Nimbus requires the client be restarted every 6 hours

### ISSUE THREAD

**Issue by ZaneCEO** [status-im/nimbus-eth2#1952]
Hi! I'm finalizing my research for my guide [Come fare staking con Ethereum 2.0](https://turbolab.it/criptovalute-bitcoin-ethereum-litecoin-4904/come-fare-staking-ethereum-2.0-guida-definitiva-configurare-tutto-guadagnare-interessi-video-3050) (italian only, sorry).

While researching the topic, I stubled upon this statement: 

> NOTE: There is currently a resource issue with Nimbus that requires the client be restarted every 6 hours. This will automatically be handled by the systemd service via RuntimeMaxSec=21600.

[source](https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-medalla-nimbus-5f4b2b0f2d7c)

Is this still true or is the bug fixed now? Do you still reccomand to use `RuntimeMaxSec=21600` in our service file?

Thanks!

**Comment by arnetheduck** [comment]
Hi, this has been resolved since, and the restart will generally not be needed - specially with the latest releases. It would be important to point out in any guide to make sure to keep the node updated however as important improvements are still happening.

**Comment by ZaneCEO** [comment]
Amazing! Thank you very much! I'm updating my guide right away. I'll also point point out to update regularly.
