### ISSUE TITLE
Allow Nimbus to work with a dynamic IP address (WAN-side)

### ISSUE THREAD

**Issue by ZaneCEO** [status-im/nimbus-eth2#1954]
**Is your feature request related to a problem? Please describe.**
I've a residential connection with a dynamic IP address assigned by the ISP: everytime I disconnect/reconnect (willingly or due to a network fault) my router gets a different public IP address. This is a most common scenario for home users.

Since [Nimbus is started with](https://turbolab.it/scarica/347) `--nat=extip:${ClientIP}` I fear (not sure?) it would stop working until the service gets restarted if the public IP address changes while the process is running. Again: I've not tested this directly.

**Describe the solution you'd like**
An option to detect this situation and handle it accordingly.

**Describe alternatives you've considered**
I've considered to prepare a bash script to detect the public IP address change and restart the Nimbus service. This is suboptimal as it requires a timed cron + polling.

**Additional context**
Again: I'm not even sure if this isn't already properly handled. First of all, I'd like to asses the current situation. Thanks!

**Comment by stefantalpalaru** [comment]
Do you have UPnP or NAT-PMP support in your router? That would get the new external IP automatically when you restart beacon_node.

(we don't handle IP changes between restarts, yet)

**Comment by ZaneCEO** [comment]
I explicitly disable UPnP because I truly believe it's a security and management abomination. So, no, auto-mapping is a no-go for me.

Anyway: handling the NAT **on restart** is a non-issue: my [service file](https://turbolab.it/scarica/347) detects the external IP and passes it on the command line, no problem. The critical issue is that I've no way to handle the IP address change **at runtime**. This is what this feature request is about.

Thanks 👍

**Comment by kdeme** [comment]
> I explicitly disable UPnP because I truly believe it's a security and management abomination. So, no, auto-mapping is a no-go for me.

Yes, that is understandable, and it wouldn't even help, as currently upnp is only used at start-up to find the external ip.

Once we get external ip discovery implemented through discoveryv5 ping-pong mechanism (https://github.com/status-im/nim-eth/issues/207) we can also use it to update the ip address in the discovery ENR while the service is running.

**Comment by ZaneCEO** [comment]
Looking good, thanks @kdeme !

**Comment by ZaneCEO** [comment]
For those who might be interested in a temporary solution: I created a script that detects IP address changes and restarts Nimbus accordingly.

The easy way to get it is via my [ethereum-autostaker](https://github.com/TurboLabIt/ethereum-autostaker) package. You don't have to use the whole thing if you don't want to. Just clone the package:

```
sudo apt install curl -y && curl -s https://raw.githubusercontent.com/TurboLabIt/ethereum-autostaker/main/setup.sh?$(date +%s) | sudo bash
```

Now run the `ip_watcher` script:

```
sudo bash /usr/local/turbolab.it/ethereum-autostaker/script/ip_watch.sh
```

This will create a cron job to auto-run it and check if the IP changed every 7 minutes.

Two critical aspect to keep in mind:

* the script restart the Nimbus service via `service nimbus restart` - change this to suite your needs
* the script pings an external, 3rd party domain (not mine) to acquire the current IP address - this is a privacy risk + it's heavily centralized

HTH

**Comment by kdeme** [comment]
PR https://github.com/status-im/nimbus-eth2/pull/2278 adds the option to allow the discovery protocol to figure out and update the IP address (based on responses from peers).

Next release will have this functionality included.
To enable it add `--enr-auto-update:true`
