### ISSUE TITLE
Eth2 deposit contract is live: what should we insert as --network to target it?

### ISSUE THREAD

**Issue by ZaneCEO** [status-im/nimbus-eth2#1955]
[Finally we have a go!](https://blog.ethereum.org/2020/11/04/eth2-quick-update-no-19/)! The deposit smart contract has been deployed.

Currently I can use `--network=medalla` or `--network=zinken` to join one of the testnets. I checked both the book and the readme, but I cannot find the value to put after the `=` to join the mainnet.

Could you please update the docs to clarify this? Also: a full list of the possible values for `--network=` would be great!

Thanks.

Edit: I suppose it's `--network=mainnet`, as documented in [eth2.0-deposit-cli](https://github.com/ethereum/eth2.0-deposit-cli) but still, I'd really love a confirmation from you guys (+ a docs update).

**Comment by arnetheduck** [comment]
Indeed - --network=mainnet will be the right option - we're about to release a new version where this becomes the default as well: https://github.com/status-im/nimbus-eth2/blob/devel/run-mainnet-beacon-node.sh

**Comment by ZaneCEO** [comment]
Looking good, thanks!
