### ISSUE TITLE
unhandled Eth1 HTTP error - crash

### ISSUE THREAD

**Issue by protolambda** [status-im/nimbus-eth2#1985]
**Describe the bug**

Nimbus errors and shuts down after hitting a HTTP status error on startup:

**To Reproduce**

Host machine:
```
uname -a
Linux  #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Running in Docker: https://github.com/protolambda/nimbus-docker/blob/master/Dockerfile

Running latest `devel`, 1774da15f15c87c88e7519f13b81f6cea1adffe0
Just the beacon node binary, with `--network=toledo`

3. Commands being executed:

```
 protolambda/nimbus:toledo         "beacon_node --network=toledo --data-dir=/data --web3-url=https://<<<snip>>> --udp-port=9000 --tcp-port=9000 --listen-address=0.0.0.0 --graffiti=@protolambda --nat=extip:<<<<snip>>> --log-level=DEBUG --rpc --rpc-port=4000 --rpc-address=0.0.0.0 --metrics --metrics-port=8080 --metrics-address=0.0.0.0 --validators-dir=/data/no_bn_keys --secrets-dir=/data/no_bn_secrets"
```

4. Relevant log lines: '...'

```
DBG 2020-11-09 18:14:01.401+00:00 Server returns error                       topics="JSONRPC-HTTP-CLIENT" tid=1 file=httpclient.nim:47 httpcode=503 httpreason="Service Temporarily Unavailable" address=<<<snip>>>
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
Traceback (most recent call last, using override)
Error: unhandled exception: Empty response from server [ValueError]
```

**Additional context**

The eth1 endpoint is a geth node behind a http proxy, it works fine for other eth2 clients.

**Comment by protolambda** [comment]
Websocket connection to infura doesn't work either.
```
libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
Traceback (most recent call last, using override)
SIGILL: Illegal operation.
```

**Comment by stefantalpalaru** [comment]
> SIGILL: Illegal operation.

You get that when compiling with `-march=native` on one CPU family and then running it on another.

Use a more recent version of the code to get backtraces for that RPC crash.

**Comment by protolambda** [comment]
```
DBG 2020-11-11 19:07:55.557+00:00 Message sent to RPC server                 topics="JSONRPC-HTTP-CLIENT" tid=1 file=httpclient.nim:188 address=52.205.94.0:80 msg_len=59
DBG 2020-11-11 19:07:55.800+00:00 Server returns error                       topics="JSONRPC-HTTP-CLIENT" tid=1 file=httpclient.nim:47 httpcode=503 httpreason="Service Temporarily Unavailable" address=52.205.94.0:80
```
Still getting the error on latest `devel`, against geth RPC.

**Comment by protolambda** [comment]
Works against infura now. Not sure why it doesn't like my geth node on initial start. Is nimbus doing some kind of request that a normal fast-synced node can't serve?

**Comment by zah** [comment]
Several fixes have been pushed to the [eth1-fixes branch](https://github.com/status-im/nimbus-eth2/pull/2004):

* The client will now produce a warning when an unsupported HTTP URL is entered. It will try to treat it as a web-socket URL, but if this is not successful, we don't consider it a fatal failure and allow the node to continue operating.

* Proxying WebSocket traffic has been tested with Nginx. You'll need to use the following configuration snippet in your nginx site definition:

```
server {
  location /ws {
    proxy_pass http://localhost:8546;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
}
```

**Comment by protolambda** [comment]
The websocket approach works, thanks.
