### ISSUE TITLE
WARN Served eth_subscribe err="notifications not supported"

### ISSUE THREAD

**Issue by ZaneCEO** [status-im/nimbus-eth2#1986]
Hi guys, someone over at /r/ethstaker [reported](https://www.reddit.com/r/ethstaker/comments/josrcl/i_wrote_a_complete_howto_guide_to_stake_ethereum/gbpi916?utm_source=share&utm_medium=web2x&context=3) this WARN:

> It seems like it is running, but I get a lot of WARN -Notifications as well:
> 
> Nov 09 11:43:38 staker-desktop geth[677]: INFO [11-09|11:43:38.224] Imported new chain segment blocks=1 txs=2 mgas=3.601 elapsed=18.069ms mgasps=199.276 number=3723088 hash="8f7516…3236d9" dirty=71.01MiB
> 
> Nov 09 11:43:40 staker-desktop geth[677]: INFO [11-09|11:43:40.176] Imported new chain segment blocks=1 txs=3 mgas=3.627 elapsed=4.305ms mgasps=842.541 number=3723088 hash="834076…a72d6b" dirty=71.01MiB
> 
> Nov 09 11:43:42 staker-desktop geth[677]: WARN [11-09|11:43:42.684] Served eth_subscribe conn=xxx.x.x.x:xxxxx reqid=1653 t="7.722µs" err="notifications not supported"

Is it important? What does it mean? Is this a configuration error we (users) can fix?

Thanks!

**Comment by zah** [comment]
This issue is a duplicate of https://github.com/status-im/nimbus-eth2/issues/1767

According to the reported information in the other issue, one possible work-around is to use a WebSocket URL (ws://...) for the web3 provider.

**Comment by ZaneCEO** [comment]
Thanks, sorry for the dupe.
