### ISSUE TITLE
Pyrmont testnet

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nimbus-eth2#2006]
https://github.com/protolambda/pyrmont - genesis likely around nov  18

New 1.0-preparation testnet that will replace medalla - the setup should be identical to medalla, except we'll have more validators to deal with - once it's up and running, we'll transfer all medalla validators to a single node that will run all medalla validators.

* [x] setup 10 nodes same as medalla
* [x] generate keys (20k)
* [x] include genesis in binary & scripts
* [x] a week later, move medalla validators to single node, shut down other medalla nodes
* [x] eventually, a week after genesis, shut down toledo

**Comment by jakubgs** [comment]
Keys: https://github.com/status-im/nimbus-private/tree/master/pyrmont_deposits

**Comment by jakubgs** [comment]
Apparently these nodes need to run `nimbus_beacon_node` instead of `nimbus_beacon_node_spec_0_12_3` as we do for `medalla`:
https://github.com/status-im/infra-nimbus/blob/81857071deeff262c8fe560cb3c5dbd5a41db86a/ansible/roles/beacon-node-builds/defaults/main.yml#L13-L25

**Comment by jakubgs** [comment]
Deployed 10 hosts in: https://github.com/status-im/infra-nimbus/commit/ad720df4

**Comment by jakubgs** [comment]
Switched builds to also build `nimbus_beacon_node`: https://github.com/status-im/infra-nimbus/commit/8c68e3b5
Before we were building only `nimbus_beacon_node_spec_0_12_3`.

**Comment by jakubgs** [comment]
Added control over entrypoint: https://github.com/status-im/infra-role-beacon-node/commit/7301c02c

**Comment by jakubgs** [comment]
Added new layout for Pyrmont: https://github.com/status-im/infra-nimbus/commit/c858cdb5

**Comment by jakubgs** [comment]
Had to increase build timeouts since we build both binaries for now: https://github.com/status-im/infra-nimbus/commit/f79d65f7

**Comment by jakubgs** [comment]
All notes are up:
```
 > ansible nimbus-slaves-pyrmont -o -a "docker ps -q --format={%raw%}'{{ .Names }}\t{{ .Status }}'{%endraw%}"
pyrmont-01.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-master	Up About an hour
pyrmont-02.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-master	Up About an hour
pyrmont-03.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-master	Up About an hour
pyrmont-04.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-master	Up About an hour
pyrmont-05.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-devel	Up 59 minutes
pyrmont-06.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-devel	Up 59 minutes
pyrmont-07.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-devel	Up 59 minutes
pyrmont-08.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-devel	Up 59 minutes
pyrmont-09.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-libp2p	Up 21 minutes
pyrmont-10.aws-eu-central-1a.nimbus.test | CHANGED | rc=0 | (stdout) beacon-node-pyrmont-libp2p	Up 21 minutes
```

**Comment by jakubgs** [comment]
I might add that we changed the layout of the nodes:
```
 > ansible localhost -m debug -a 'var=groups["nimbus.pyrmont"]'
localhost | SUCCESS => {
    "groups[\"nimbus.pyrmont\"]": [
        "devel-large-01.aws-eu-central-1a.nimbus.pyrmont",
        "devel-large-02.aws-eu-central-1a.nimbus.pyrmont",
        "devel-small-01.aws-eu-central-1a.nimbus.pyrmont",
        "devel-small-02.aws-eu-central-1a.nimbus.pyrmont",
        "devel-small-03.aws-eu-central-1a.nimbus.pyrmont",
        "devel-small-04.aws-eu-central-1a.nimbus.pyrmont",
        "libp2p-small-01.aws-eu-central-1a.nimbus.pyrmont",
        "libp2p-small-02.aws-eu-central-1a.nimbus.pyrmont",
        "master-large-01.aws-eu-central-1a.nimbus.pyrmont",
        "master-large-02.aws-eu-central-1a.nimbus.pyrmont",
        "master-small-01.aws-eu-central-1a.nimbus.pyrmont",
        "master-small-02.aws-eu-central-1a.nimbus.pyrmont",
        "master-small-03.aws-eu-central-1a.nimbus.pyrmont",
        "master-small-04.aws-eu-central-1a.nimbus.pyrmont"
    ]
}
```
