### ISSUE TITLE
Github actions build will presumably start failing nov16

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nimbus-eth2#2009]
Seen in build on windows:

```
Error: The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by sinkingsugar** [comment]
I had a couple of those on some of my own repos, this is a workaround:
```
env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
```

**Comment by arnetheduck** [comment]
when will the unsecure commands get deprecated for real?

**Comment by sinkingsugar** [comment]
The problem is some action we are using to fetch msys I think, the vulnerability is path injection https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w
Once the msys is fixed can be turned off
