### ISSUE TITLE
Add "stable" docker tag

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nimbus-eth2#2019]
## Feature request

Currently, a `devel` docker tag exists, that tracks development on `devel`.

In addition to this, a `stable` tag would be useful, that tracks latest release. This makes docker tooling easier,
as there's no need to change configuration files with a new release.

I have no opinion on the exact name of such a tag. There might be a `release-1.x` as well or instead, to go with semantic versioning and avoid pulling in breaking changes, similar to how geth has `stable` and `release-1.9`.

**Comment by stefantalpalaru** [comment]
> Currently, a devel docker tag exists, that tracks development on devel.

We don't have Docker tags at all. We don't release Docker images. We only release binaries.

**Comment by zah** [comment]
We plan to release docker images though and we are likely to follow the suggestion here.

**Comment by protolambda** [comment]
I've been building my own nimbus docker images for over a year now, and since about two weeks they stopped being compatible between different amd64 machines. There's some work to do, with more tags than just `latest`.

**Comment by mFarghaly** [comment]
please update your build pipeline to push docker images to dockerhub tagged with the relevant release tag i.e `v1.0.4`
It should include all binaries.

**Comment by stefantalpalaru** [comment]
Done: https://hub.docker.com/r/statusim/nimbus-eth2
