### ISSUE TITLE
JSON-RPC current state

### ISSUE THREAD

**Issue by cheatfate** [status-im/nimbus-eth2#2029]
This is current state of our JSON-RPC calls.
Initial documentation and information obtained from here https://ethereum.github.io/eth2.0-APIs/ using https://ethereum.github.io/eth2.0-APIs/beacon-node-oapi.yaml

|N|Request name | Request type | Status |
|:---|:--- |:---:|:---:|
| 1 | /eth/v1/beacon/genesis | GET | :heavy_check_mark: |
| 2 | /eth/v1/beacon/states/{state_id}/root | GET | :heavy_check_mark: |
| 3 | /eth/v1/beacon/states/{state_id}/fork | GET | :heavy_check_mark: |
| 4 | /eth/v1/beacon/states/{state_id}/finality_checkpoints | GET | :heavy_check_mark: |
| 5 | /eth/v1/beacon/states/{state_id}/validators | GET | :heavy_check_mark: |
| 6 | /eth/v1/beacon/states/{state_id}/validators/{validator_id} | GET | :heavy_check_mark: |
| 7 | /eth/v1/beacon/states/{state_id}/validator_balances | GET | :heavy_check_mark: |
| 8 | /eth/v1/beacon/states/{state_id}/committees | GET | :heavy_check_mark: |
| 9 | /eth/v1/beacon/headers [[1]](https://github.com/status-im/nimbus-eth2/issues/2029#issuecomment-733711620) | GET | :x: |
| 10 | /eth/v1/beacon/headers/{block_id} | GET | :heavy_check_mark: |
| 11 | /eth/v1/beacon/blocks | POST | :heavy_check_mark: |
| 12 | /eth/v1/beacon/blocks/{block_id} | GET | :heavy_check_mark: |
| 13 | /eth/v1/beacon/blocks/{block_id}/root | GET | :heavy_check_mark: |
| 14 | /eth/v1/beacon/blocks/{block_id}/attestations | GET | :heavy_check_mark: |
| 15 | /eth/v1/beacon/pool/attestations | GET | :heavy_check_mark: |
| 16 | /eth/v1/beacon/pool/attestations | POST | :heavy_check_mark: |
| 17 | /eth/v1/beacon/pool/attester_slashings | GET | :heavy_check_mark: |
| 18 | /eth/v1/beacon/pool/attester_slashings | POST | :heavy_check_mark: |
| 19 | /eth/v1/beacon/pool/proposer_slashings | GET | :heavy_check_mark: |
| 20 | /eth/v1/beacon/pool/proposer_slashings | POST | :heavy_check_mark: |
| 21 | /eth/v1/beacon/pool/voluntary_exits | GET | :heavy_check_mark: |
| 22 | /eth/v1/beacon/pool/voluntary_exits | POST | :heavy_check_mark: |
| 23 | /eth/v1/debug/beacon/states/{state_id} | GET | :heavy_check_mark: |
| 24 | /eth/v1/debug/beacon/heads | GET | :heavy_check_mark: |
| 25 | /eth/v1/node/identity | GET | :heavy_check_mark: |
| 26 | /eth/v1/node/peers | GET | :heavy_check_mark: |
| 27 | /eth/v1/node/peers/{peer_id} | GET | :heavy_check_mark: |
| 28 | /eth/v1/node/peer_count | GET | :heavy_check_mark: |
| 29 | /eth/v1/node/version | GET | :heavy_check_mark: |
| 30 | /eth/v1/node/syncing | GET  | :heavy_check_mark: |
| 31 | /eth/v1/node/health | GET | :heavy_check_mark: |
| 32 | /eth/v1/config/fork_schedule | GET | :heavy_check_mark: |
| 33 | /eth/v1/config/spec | GET | :heavy_check_mark: |
| 34 | /eth/v1/config/deposit_contract | GET | :heavy_check_mark: |
| 35 | /eth/v1/validator/duties/attester/{epoch} | POST | :heavy_check_mark: |
| 36 | /eth/v1/validator/duties/proposer/{epoch} | GET | :heavy_check_mark: |
| 37 | /eth/v1/validator/blocks/{slot} | GET | :heavy_check_mark: |
| 38 | /eth/v1/validator/attestation_data | GET | :heavy_check_mark: |
| 39 | /eth/v1/validator/aggregate_attestation | GET | :heavy_check_mark: |
| 40 | /eth/v1/validator/aggregate_and_proofs | POST | :heavy_check_mark: |
| 41 | /eth/v1/validator/beacon_committee_subscriptions | POST | :x: |
| 42 | /eth/v1/events | GET | :x: |

**Comment by cheatfate** [comment]
With current database scheme and DAG implementation its impossible to implement `/eth/v1/beacon/headers` efficiently, because of `parent_root` parameter.

**Comment by arnetheduck** [comment]
The REST api implements the full spec, as of 1.5.0.
