### ISSUE TITLE
Simplify deposits import command

### ISSUE THREAD

**Issue by sachayves** [status-im/nimbus-eth2#2067]
**Is your feature request related to a problem? Please describe.**
Many users are having trouble specifying the data directory correctly when importing keys

**Describe the solution you'd like**
By default search for the `validator_keys` directory next to the `nimbus_eth2` directory (if no data directory path is specified)

If we can't find it then we throw an error message that says one should either copy the `validator_keys` directory to the expected location, or run the command with a specified data directory.

Make the above clear in the book.

**Describe alternatives you've considered**
Automagic import (not possible since relevant directory could be saved anywhere)

**Additional context**
None

**Comment by zah** [comment]
Implemented slightly differently in the above PR and approved by @sachayves. Documentation will come shortly.
