### ISSUE TITLE
Nimbus only wants to talk with Geth for ETH1

### ISSUE THREAD

**Issue by xachen** [status-im/nimbus-eth2#2072]
**Describe the bug**
Nimbus only wants to work with either Geth or Infura (which uses Geth) for ETH1 logs. Besu does not want to communicate. I know Besu is configured correctly since Teku and Lighthouse connect correctly to it.

**To Reproduce**
1. Platform details (OS, architecture): '...'
justin@bullwinkle:~/pyrmont$ uname -a
Linux bullwinkle 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

2. Branch/commit used: '...'
justin@bullwinkle:~/pyrmont/nimbus-eth2$ git log -1
commit 7b7dc6fed4763914a191f2c4e5054e19c5126467 (HEAD -> devel, origin/devel)

(same issue on latest master)

3. Commands being executed: '...'
WEB3_URL="ws://127.0.0.1:8546" ./run-pyrmont-beacon-node.sh --log-level=TRACE
4. Relevant log lines: '...'
justin@bullwinkle:~/pyrmont/nimbus-eth2$ ./run-pyrmont-beacon-node.sh --log-level=TRACE

To monitor the Eth1 validator deposit contract, you'll need to pair
the Nimbus beacon node with a Web3 provider capable of serving Eth1
event logs. This could be a locally running Eth1 client such as Geth
or a cloud service such as Infura. For more information please see
our setup guides:

https://status-im.github.io/nimbus-eth2/eth1.html

Please enter a Web3 provider URL: ws://127.0.0.1:8546
WRN 2020-11-24 14:01:49.025-07:00 You are running an alpha version of Nimbus - it is not suitable for mainnet! topics="beacnde" tid=14291 file=nimbus_beacon_node.nim:1135 version=v0.6.6-7b7dc6fe
INF 2020-11-24 14:01:49.025-07:00 Launching beacon node                      topics="beacnde" tid=14291 file=nimbus_beacon_node.nim:1137 version=v0.6.6-7b7dc6fe bls_backend=BLST cmdParams="@[\"--network=pyrmont\", \"--data-dir=build/data/shared_pyrmont_0\", \"--log-file=build/data/shared_pyrmont_0/nbc_bn_20201124140149.log\", \"--web3-url=ws://127.0.0.1:8546\", \"--tcp-port=9000\", \"--udp-port=9000\", \"--rpc\", \"--rpc-port=9190\", \"--log-level=TRACE\"]" config="(logLevel: \"TRACE\", logFile: Some(build/data/shared_pyrmont_0/nbc_bn_20201124140149.log), eth2Network: Some(\"pyrmont\"), dataDir: build/data/shared_pyrmont_0, validatorsDirFlag: None[InputDir], secretsDirFlag: None[InputDir], walletsDirFlag: None[InputDir], web3Url: \"ws://127.0.0.1:8546\", depositContractAddress: Some(0x8c5fecdc472e27bc447696f431e425d02dd46a8c), depositContractDeployedAt: Some((isHash: false, number: 3743587)), nonInteractive: false, netKeyFile: \"random\", netKeyInsecurePassword: false, cmd: noCommand, bootstrapNodes: @[\"# @protolambda bootnode 1\", \"enr:-Ku4QOA5OGWObY8ep_x35NlGBEj7IuQULTjkgxC_0G1AszqGEA0Wn2RNlyLFx9zGTNB1gdFBA6ZDYxCgIza1uJUUOj4Dh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDVTPWXAAAgCf__________gmlkgnY0gmlwhDQPSjiJc2VjcDI1NmsxoQM6yTQB6XGWYJbI7NZFBjp4Yb9AYKQPBhVrfUclQUobb4N1ZHCCIyg\", \"# @protolambda bootnode 2\", \"enr:-Ku4QOksdA2tabOGrfOOr6NynThMoio6Ggka2oDPqUuFeWCqcRM2alNb8778O_5bK95p3EFt0cngTUXm2H7o1jkSJ_8Dh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDVTPWXAAAgCf__________gmlkgnY0gmlwhDaa13aJc2VjcDI1NmsxoQKdNQJvnohpf0VO0ZYCAJxGjT0uwJoAHbAiBMujGjK0SoN1ZHCCIyg\", \"# lighthouse bootnode 1\", \"enr:-LK4QDiPGwNomqUqNDaM3iHYvtdX7M5qngson6Qb2xGIg1LwC8-Nic0aQwO0rVbJt5xp32sRE3S1YqvVrWO7OgVNv0kBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhBKNA4qJc2VjcDI1NmsxoQKbBS4ROQ_sldJm5tMgi36qm5I5exKJFb4C8dDVS_otAoN0Y3CCIyiDdWRwgiMo\", \"# lighthouse bootnode 2\", \"enr:-LK4QKAezYUw_R4P1vkzfw9qMQQFJvRQy3QsUblWxIZ4FSduJ2Kueik-qY5KddcVTUsZiEO-oZq0LwbaSxdYf27EjckBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhCOmkIaJc2VjcDI1NmsxoQOQgTD4a8-rESfTdbCG0V6Yz1pUvze02jB2Py3vzGWhG4N0Y3CCIyiDdWRwgiMo\", \"# nimbus bootnodes\", \"enr:-LK4QK6e16UnTLbi8mJuXHdUSNN8BUcUqhnhyy2bL2_JeX7iMfK9lRbtq8M4kMDGhFwyUQLkHxaDNxS0IPuGS53c1osBh2F0dG5ldHOI__________-EZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhAN_0AGJc2VjcDI1NmsxoQOPQv1VILGXeB10y088SeuU6-w8Yh689Fv_uWjhtFqbLIN0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QHy7BBDm_mxT0i-EBatHvHGfzNH4BcaAdNguNS8fuaxFDfHP0qVJ9f9A38Q_lMmRUK5PSVHEEoC1mwrExO51T2cBh2F0dG5ldHOI__________-EZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhBLGXiqJc2VjcDI1NmsxoQJV51WZn_NLj-0vHAmmZ6tWtzIdu-P_xVr7k9zMEkvaA4N0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QE8QIkEl2k67fj53vn6SgLwj07ElmWZJrIeEpZUfh91oe-PNAlIzeRwI47_wZTK1S2KretXF56XkZqP0v5VlBVUBh2F0dG5ldHOI__________-EZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhBLB_8yJc2VjcDI1NmsxoQOEowpACJVUFtcWKhpEk9HlEyY4AEcTB4fONkPEvpeYmIN0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QJMF9O8D7hNcGP1Xxh5E09lxUwrzFwokYDxIxUjj_yOnDOWX5HjTDJ4TLZle3HVozC3vJuiZF7jImJMt79t8FuYBh2F0dG5ldHOI__________-EZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhBKeOTGJc2VjcDI1NmsxoQJLajuu1S9v-NREUDo5kzUY-ook9CqYLDiHf8z1nMSY1oN0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QOTyWBISU1AysyKFt35m_epniDd54LEAsTS2x0OSo1FFTY2ZxETVm43VcZYkmYMQo2ECUAV-0RwAFZcC9_xjRQ4Bh2F0dG5ldHOI__________-EZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhAN9a7CJc2VjcDI1NmsxoQJCIUgdHgGuE_k9CVThmgiiXXYW1lfdCZbWHj4p_SAkY4N0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QHOOeQg3HjXSGoXGZPJYeBQ3o9beIGLU1Fxv2PIZX5NEeBLJPB9kpP5xNX_dJ23lsZ0RhBwAxXXTtziC9EMuZuMBh2F0dG5ldHOI__________-EZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhCOc7_OJc2VjcDI1NmsxoQPMp2C3hjMNBt6Dr4npyfTG0__GpHtxYXrnho4lT2g2c4N0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QOMpgA7LUM-YUJqWWGX1t01wJkqDMjDJrhxyJHp7ZOCyWkJEYqkHOHYms_K6PI0Ky9Bw57R3ayk9LzE5E9v54WEBh2F0dG5ldHOI__________-EZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhBLApGOJc2VjcDI1NmsxoQNGyxAQW2ZUvt_n-MZByer467sfBWclC3pJtvnZDaLhZYN0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QL3Y2elAiia5WV18p_pu9t_7syTsZs-rWGD6_IHhiEvBUIzZtT88VMsI-rN8fNSukaHuq7qtDhZwRISdG9O4uQsBh2F0dG5ldHOI__________-EZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhBLGowKJc2VjcDI1NmsxoQK13jMsuO1LbguOsFZ0hxvRe7PT8V1W9qeUMs6fgiwuM4N0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QAtPY91umFgpKmvSEcsDdzXxB6Ss5pa55oqk-t58Uv9qF-B68jEjsN7B_SBGe4qCH1thKwokbS8-zC8Xy-NsED8Bh2F0dG5ldHOI__________-EZXRoMpDzGkhaAAAAAP__________gmlkgnY0gmlwhBKeqH2Jc2VjcDI1NmsxoQIRA0fHAr6eECjjIZZK-GB6dE0awWYtTrOMACfjq12M5oN0Y3CCI4yDdWRwgiOM\", \"enr:-LK4QLvxqICUmpMitpwHDwJNEUGj1ecsW_ZlGImx6SwfyFJICV2SO6lYcdxDKHAK0RzdWYo8dGm3tL__NpP_4Afy5psBh2F0dG5ldHOI__________-EZXRoMpDzGkhaAAAAAP__________gmlkgnY0gmlwhBLBEDqJc2VjcDI1NmsxoQJw2JPyabX2G_f9eAkbjhBDshIeUP-eZ-KoMGqFTdxUToN0Y3CCI4yDdWRwgiOM\", \"\"], bootstrapNodesFile: , listenAddress: 0.0.0.0, tcpPort: 9000, udpPort: 9000, maxPeers: 79, nat: \"any\", weakSubjectivityCheckpoint: None[Checkpoint], finalizedCheckpointState: None[InputFile], finalizedCheckpointBlock: None[InputFile], runtimePreset: (GENESIS_FORK_VERSION: 00002009, GENESIS_DELAY: 432000, MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 16384, MIN_GENESIS_TIME: 1605700800, ETH1_FOLLOW_DISTANCE: 2048), nodeName: \"\", graffiti: None[GraffitiBytes], verifyFinalization: false, stopAtEpoch: 0, metricsEnabled: false, metricsAddress: 127.0.0.1, metricsPort: 8008, statusBarEnabled: true, statusBarContents: \"peers: $connected_peers;finalized: $finalized_root:$finalized_epoch;head: $head_root:$head_epoch:$head_epoch_slot;time: $epoch:$epoch_slot ($slot);sync: $sync_status|\", rpcEnabled: true, rpcPort: 9190, rpcAddress: 127.0.0.1, inProcessValidators: true, discv5Enabled: true, dumpEnabled: false)"
INF 2020-11-24 14:01:49.038-07:00 Loading block dag from database            topics="beacnde" tid=14291 file=nimbus_beacon_node.nim:198 path=build/data/shared_pyrmont_0/db
INF 2020-11-24 14:01:49.518-07:00 Block dag initialized                      topics="beacnde" tid=14291 file=chain_dag.nim:423 head=da778bb6:123 finalizedHead=6a89af5d:0 tail=6a89af5d:0 totalBlocks=88
ERR 2020-11-24 14:01:49.520-07:00 Failed to start Eth1 monitor               topics="beacnde" tid=14291 file=nimbus_beacon_node.nim:241 reason="Failed to setup web3 connection" web3Url=ws://127.0.0.1:8546 depositContractAddress=0x8c5fecdc472e27bc447696f431e425d02dd46a8c depositContractDeployedAt="(isHash: false, number: 3743587)"
INF 2020-11-24 14:01:49.520-07:00 Starting JSON-RPC HTTP server              topics="JSONRPC-HTTP-SERVER" tid=14291 file=httpserver.nim:215 url=http://127.0.0.1:9190
INF 2020-11-24 14:01:49.524-07:00 Generating new networking key              topics="networking" tid=14291 file=eth2_network.nim:1251 network_public_key=08021221025c25008a81365ceaa82e88e23998216c9b160243797252979e2c9daa54f76350 network_peer_id=16Uiu2HAm1dNDJxduVzKqJGcYBLg137iLsaoWGSUju2FKGKB9iiZd

**Comment by zah** [comment]
Support for Besu is likely to be added in our first point release after the v1.0.0. The issue has been tracked down to a compatibility issue present in one of the few third-party packages that we use. A fix has been pushed here and will be proposed to the upstream project:

https://github.com/status-im/news/pull/1

**Comment by eccentricexit** [comment]
Apparently erigon is also not supported. Running nimbus with a fully synced erigon node gives the following loop (failing to connect):
`err: Failed to setup web3 connection`

```
Dec 14 11:11:38 ghostshell run-mainnet-beacon-node.sh[27923]: INF 2021-12-14 11:11:38.321-03:00 Starting Eth1 deposit contract monitoring  topics="eth1" contract=0x00000000219ab540356cbb839cbe05303d7705fa url=wss://127.0.0.1:8545
Dec 14 11:11:38 ghostshell run-mainnet-beacon-node.sh[27923]: WRN 2021-12-14 11:11:38.323-03:00 Eth1 chain monitoring failure, restarting  topics="eth1" err="Trying to access value with err: Failed to setup web3 connection"
Dec 14 11:11:40 ghostshell run-mainnet-beacon-node.sh[27923]: WRN 2021-12-14 11:11:40.652-03:00 Discovery send failed                      topics="discv5" msg="(1) Operation not permitted"
Dec 14 11:11:43 ghostshell run-mainnet-beacon-node.sh[27923]: INF 2021-12-14 11:11:43.480-03:00 Starting Eth1 deposit contract monitoring  topics="eth1" contract=0x00000000219ab540356cbb839cbe05303d7705fa url=wss://127.0.0.1:8545
Dec 14 11:11:44 ghostshell run-mainnet-beacon-node.sh[27923]: WRN 2021-12-14 11:11:44.804-03:00 Eth1 chain monitoring failure, restarting  topics="eth1" err="Trying to access value with err: Failed to setup web3 connection"
Dec 14 11:11:47 ghostshell run-mainnet-beacon-node.sh[27923]: INF 2021-12-14 11:11:47.037-03:00 Reached new finalization checkpoint        topics="chaindag" head=92f97cd3:2719008 stateRoot=5fe10899 justified=84968:a93e9900 finalized=84967:69763141 newHead=92f97cd3:2719008
Dec 14 11:11:47 ghostshell run-mainnet-beacon-node.sh[27923]: INF 2021-12-14 11:11:47.038-03:00 Slot start                                 topics="beacnde" slot=2722257 epoch=85070 sync="PPPPPPPwPP:9:0.1240:07h19m (2718985)" peers=9 head=92f97cd3:2719008 finalized=84967:69763141 delay=38ms528us745ns
Dec 14 11:11:47 ghostshell run-mainnet-beacon-node.sh[27923]: INF 2021-12-14 11:11:47.278-03:00 Slot end                                   topics="beacnde" slot=2722257 nextActionWait=n/a nextAttestationSlot=-1 nextProposalSlot=-1 head=92f97cd3:2719008
Dec 14 11:11:48 ghostshell run-mainnet-beacon-node.sh[27923]: NOT 2021-12-14 11:11:48.402-03:00 Shutting down after having received SIGTERM topics="beacnde"
Dec 14 11:11:48 ghostshell systemd[1]: Stopping Nimbus service...
Dec 14 11:11:48 ghostshell run-mainnet-beacon-node.sh[27923]: NOT 2021-12-14 11:11:48.608-03:00 Graceful shutdown                          topics="beacnde"
Dec 14 11:11:49 ghostshell run-mainnet-beacon-node.sh[27923]: INF 2021-12-14 11:11:49.866-03:00 Starting Eth1 deposit contract monitoring  topics="eth1" contract=0x00000000219ab540356cbb839cbe05303d7705fa url=wss://127.0.0.1:8545
Dec 14 11:11:50 ghostshell run-mainnet-beacon-node.sh[27923]: WRN 2021-12-14 11:11:50.703-03:00 Eth1 chain monitoring failure, restarting  topics="eth1" err="Trying to access value with err: Failed to setup web3 connection"
```

Commands:
```
erigon --datadir=/srv/erigon/erigon_data --private.api.addr=localhost:9090 --metrics
rpcdaemon --datadir=/srv/erigon/erigon_data --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool --ws
run-mainnet-beacon-node.sh --web3-url="wss://127.0.0.1:8545" --data-dir=/srv/nimbus/nimbus_data --metrics --enr-auto-update:true --nat:extip:<my-ip>
```
Client versions:
```
erigon --version
erigon version 2021.12.1-beta

nimbus_beacon_node --version
Nimbus beacon node v1.5.5-f0f973-stateofus
Copyright (c) 2019-2021 Status Research & Development GmbH

eth2 specification v1.1.6

Nim Compiler Version 1.2.14 [Linux: amd64]
```

**Comment by zah** [comment]
This issue has been resolved shortly after the comment above
