### ISSUE TITLE
Pre-start mainnet ETH balance reported is always 0

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nimbus-eth2#2120]
No matter how many validators are attached, the balance reported is 0.
This might be a bit misleading to the users.
I suppose once the network starts will be correct.

**Comment by zah** [comment]
It's actually worse. The right balance is not reported until you are synced.

**Comment by arnetheduck** [comment]
Fixed in 1.0.4: https://github.com/status-im/nimbus-eth2/pull/2191
