### ISSUE TITLE
[Mainnet launch] Crash in bufferstream

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#2129]
Discord
![image](https://user-images.githubusercontent.com/22738317/100777751-832acb00-3406-11eb-97fb-16cf63e49a91.png)

> libbacktrace error: no debugging symbols available. Compile with '--debugger:native'.
Traceback (most recent call last, using override)
Error: unhandled exception: /nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(108, 11) not s.reading Only one concurrent read allowed [AssertionError]

@dryajov mentioned that it is known and will be fixed in an upcoming version

**Comment by dryajov** [comment]
Yes, this should be addressed by https://github.com/status-im/nim-libp2p/pull/466.
