### ISSUE TITLE
Provide ARM64 release binary for Raspberry Pi

### ISSUE THREAD

**Issue by f5b7** [status-im/nimbus-eth2#2136]
I'm currently staking with a Raspberry Pi 4, using Prysm and Lighthouse. I would like to try Nimbus because on the Genesis live stream I heard that it may be more suited for lower-end devices like the Raspberry Pi.

Providing pre-built binaries for 64-bit ARM processors (Prysm marks them as `arm64`, Lighthouse as `aarch64`) will make it much more convenient to set up and update Nimbus on a Raspberry Pi. This again will help improve staking client diversity.

**Comment by stefantalpalaru** [comment]
Done.
