### ISSUE TITLE
Subscribe to random attestation subnets also in case you have no validators? 

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth2#2144]
According to the specification you currently have to subscribe to 1 random subnet per validator: https://github.com/ethereum/eth2.0-specs/blob/v1.0.0/specs/phase0/validator.md#phase-0-attestation-subnet-stability

Does this mean that non validator nodes don't subscribe to any of the attestation topics?
Would it not make sense that a beacon node without validators would also subscribe to some random subnets? 
Else it seems trivial to distinguish beacon nodes with validators versus ones without?

**Comment by kdeme** [comment]
I was checking the metrics and the `libp2p_pubsub_topics` gives 69.0 also in case you have no validators attached. So if that metric is correct, then we already do the above, to perhaps a too great extend :)

We seem to start with subscribing to all https://github.com/status-im/nimbus-eth2/blob/43662be3f8791998718e885cdaa39672bcafa108/beacon_chain/nimbus_beacon_node.nim#L439

But expired ones never unsubscribed in case of no validators? https://github.com/status-im/nimbus-eth2/blob/43662be3f8791998718e885cdaa39672bcafa108/beacon_chain/nimbus_beacon_node.nim#L392

**Comment by tersec** [comment]
Yeah.

The subscribing to all was a way of being cautious around not missing attestation/block proposals in that first period, but it could be tightened.

Pretending it's responsible for some random validator for subnet purposes solves that conveniently though. So addressing the main topic of this issue also fixes what you discovered.

**Comment by kdeme** [comment]
OK, it looks like for non validators we subscribe always to all attestation topics and never unsubscribe.
Not sure if this was intentional, but I guess an improvement would be to select a random set and change it now and then?

**Comment by tersec** [comment]
It would, yes. My plan is, when there are no validators attached, pick a random validator index and follow its subnets.

**Comment by arnetheduck** [comment]
hm I see two use cases here: 

* node that wants to follow head but keep bandwidth low - this one should not subscribe to attestation or aggregation subnets
* node that wants to do good for the network - this one should subscribe to a number of subnets depending on appetite for bandwidth usage - maybe we should simply have an `--extra-subnets` option?

**Comment by tersec** [comment]
nbc doesn't subscribe to any of its attestation subnets anymore, except when the spec requires it for aggregating. So this issue as written has been overtaken by the code/specs.

`--extra-slots` is still something one could argue for (though `--subscribe-all-subnets` already exists, so it's a question of how useful the middle ground is).
