### ISSUE TITLE
Nimbus book: page on safety precautions to take when migrating keys over to another machine

### ISSUE THREAD

**Issue by unixpi** [status-im/nimbus-eth2#2156]
resources:
https://discord.com/channels/624205794384281629/740564053080014900/785482606203895838

h/t @oskarth

**Comment by sachayves** [comment]
"As a rule of thumb then for the book:

1) Ensure node is off
2) Move keys with <tbd procedure>
3) Ensure NTP/time is correctly set on new node
4) Import/create new slashing protection db for validators
5) Wait 2 epochs + possible time offset + small buffer, ~-=15m assuming synced nodes
I see, so this 2 epoch thing is automated? no need to care about that manually?
https://ethresear.ch/t/eth2-attack-via-time-servers/8049/8 interesting attack
afk bed"

**Comment by oskarth** [comment]
Thanks for creating the issue @sachayves!

cc @mratsim @arnetheduck - it'd be good to (1) verify that it this is accurate (2) minimize requirements/manual work needed (e..g seems like the "wait two epochs" might be done automatically upon import?)

**Comment by mratsim** [comment]
Covered by https://nimbus.guide/migration.html
