### ISSUE TITLE
RPC method to obtain current epoch

### ISSUE THREAD

**Issue by unixpi** [status-im/nimbus-eth2#2165]
*Discord feature request*

rramos: @tersec, do you know which rpc method I could use to obtain the current epoch?

tersec: oddly, I can't find one. Maybe I'm missing it
a lot of individual RPC calls first start by getting the current epoch, but then do something else with it. I don't see a non-kludgy way to get the epoch interface out of the RPCs though.

rramos: ah :frowning: sad.
I'll use beaconcha.in's API to get that in the meantime

**Comment by zah** [comment]
There are several ways to compute the current epoch:

1) You can use the `getBeaconHead` API to get the head slot. To arrive at the epoch, you can either divide by 32 (on mainnet) or use the `get_v1_config_spec` API to get the `SLOTS_PER_EPOCH` (on any network). Please note that this would obtain the "subjective" head epoch as seen by the current beacon node.

2) You can get the network genesis time with `get_v1_beacon_genesis`. You can then use the wall clock and the `SECONDS_PER_SLOT` constant to obtain the "objective" epoch that all fully synced clients should be at.
