### ISSUE TITLE
Nimbus book: Add page on updating eth1 client

### ISSUE THREAD

**Issue by unixpi** [status-im/nimbus-eth2#2176]
"on Mac or Linux, you can
- build a new geth in a different directory
- rename the old Geth to geth-old (while it's running, no problem)
- start the new geth (you might need to kill the old one as it might have reserved some ports)
- restart the eth2 client.

As an extra optimization, you can restart once you confirm from beaconcha.in that your scheduled attestation has been sent."

h/t @mratsim

**Comment by mratsim** [comment]
@arnetheduck had a comment that Eth1 monitoring was only necessary for block production which is a rare event so the Eth1 client can be restarted more freely.


That said if Eth2 evolves to use secret leader election that won't be true anymore. (but this is months away)
