### ISSUE TITLE
Nimbus doesn't work through trickle (bandwidth shaper)

### ISSUE THREAD

**Issue by ZaneCEO** [status-im/nimbus-eth2#2212]
I'm running Nimbus v1.0.4 on an Ubuntu 20.04 fully up-to-date PC. I'm doing this just on testnet, to get a better understanding of the Ethereum 2.0 tools for my [italian guide on staking](https://turbolab.it/criptovalute-bitcoin-ethereum-litecoin-4904/come-fare-staking-ethereum-2.0-guida-definitiva-configurare-tutto-guadagnare-interessi-testnet-pyrmont-mainnet-video-3050). I run it at home, on my crappy italian connection.

The Go Ethereum node is on the same PC.

I usually run Nimbus demonized like this:

````
[Unit]
Description=Nimbus (testnet)
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=nimbus
Group=nimbus
Restart=on-failure
RestartSec=5
WorkingDirectory=/var/lib/nimbus
Environment="ClientIP=$(curl -s v4.ident.me)"
ExecStart=/bin/bash -c '/usr/local/bin/nimbus --network=pyrmont --data-dir=/var/lib/nimbus --web3-url=ws://127.0.0.1:8546 --nat=extip:${ClientIP} --validators-dir=/var/lib/nimbus/validators --secrets-dir=/var/lib/nimbus/secrets --log-level=INFO --log-file=/var/lib/nimbus/beacon_node.log'

[Install]
WantedBy=multi-user.target
````

This usually works beatifully ([my testnet validator is here](https://pyrmont.beaconcha.in/validator/0xa3a9fa16a04b434963d34f996dc4cdcc7f66023f583289d1f2bf4cf08f4d672efed14103122752eb2398e3ae7c9d7c5c)) but I noticed that it consumes more bandwidth than I'd like.

So now I'm trying to shape the connection using [Trickle](http://manpages.ubuntu.com/manpages/bionic/man1/trickle.1.html). The demonized Nimbus above was updated like this:

````
...
ExecStart=/bin/bash -c 'trickle -s -u 80 /usr/local/bin/nimbus --network=pyrmont ......
...
````

The problems is that, as soon as I put Trickle in front of it, Nimubs no longer finds peers:

````
Jan 05 22:19:41 lark bash[1083]: NOT 2021-01-05 22:19:36.745+01:00 Peer count low, no new peers discovered    topics="networking" tid=1083 file=eth2_network.nim:918 discovered=34 new_peers=0 current_peers=1 wanted_peers=160
````

The problem doesn't seems to be the traffic shaping itself. Even if I set the limit to "unlimited", Nimbus has the same problem.

Could you please look into it and make Nimubs compatible or advise what I'm doing wrong? If not: is there any other traffic shaping solution I can use to reduce the bandwidth consumed by Nimbus, expecially on the upstream side?

Thanks!

**Comment by tersec** [comment]
The first thing I'd check, to fix this at a more fundamental level than using trickle, is the `unstable` branch, which has a fix relating to attestation subnet subscribing and unsubscribing that can save quite a bit of bandwidth.

The issue with using trickle is that while it's possible for an Eth2 client to deviate in semi-harmless ways from the spec and reduce its bandwidth consumption, trickle has no idea what's important and what's not for Eth2. It's not going to keep peers easily when it doesn't actively participate with them: given a certain set of gossip topics it's subscribed to, it doesn't, in theory, have a lot of freedom to choose which particular messages it relays or doesn't relay, and other nodes will tend to note inactivity, penalize it, and disconnect. This isn't just going to be an issue with trickle, but any external bandwidth-shaping tool.

A more Eth2-correct way of doing this is to only subscribe to the attestation subnets one actually should be on, which `unstable` does, but the current `stable` 1.0.4 does not, instead staying on many more subnets than it needs.

**Comment by stefantalpalaru** [comment]
It won't work on anything other than TCP and `select()`:

https://github.com/mariusae/trickle/issues/25

https://www.usenix.org/legacy/event/usenix05/tech/freenix/full_papers/eriksen/eriksen.pdf

**Comment by ZaneCEO** [comment]
hi @tersec, thanks for your reply.

Thanks for the `unstable` tip, I'll try and switch to it this weekend.

As for the shaping matter: I see what you mean. Yes, contributing less to the peers isn't ideal, but as long as you keep it within reasonable levels, I think they'll perceive my node as an "OK" node and maintain the connection nonetheless. What "reasonable" mean, I've no idea ([the book](https://status-im.github.io/nimbus-eth2/hardware.html) doesn't say): I'm now trying with a 1 megabit per second at the interface level (cumulative for Go Ethereum+Nimbus) and see how it goes.

As per my Trickle problem: I think I found the issue. From the [man page](https://linux.die.net/man/1/trickle):

> Currently, trickle supports the shaping of any SOCK_STREAM (see socket(2)) connection established via the socket(2) interface. Furthermore, trickle will not work with statically linked executables, nor with setuid(2) executables

I suspect that Nimbus uses something else to connect, so probably this isn't fixable.

So: I switched from Trickle to *Traffic Control* (`tc`). It's WAY more complex, but I copied bits and pieces around and I ran this:

````
tc qdisc add dev wlo2 root tbf rate 1mbit burst 10kb latency 70ms peakrate 1.5mbit minburst 1540
````

The peers are rising again

````
Jan 06 00:07:19 lark bash[3955]: NOT 2021-01-06 00:06:57.209+01:00 Peer count low, no new peers discovered    topics="networking" tid=3955 file=eth2_network.nim:918 discovered=26 new_peers=0 current_peers=39 wanted_peers=160
````

I checked on the router and the bandwidth seems within the set parameters. So it's probably solved.

**Comment by ZaneCEO** [comment]
> It won't work on anything other than TCP and `select()`:
> 
> [mariusae/trickle#25](https://github.com/mariusae/trickle/issues/25)
> 
> https://www.usenix.org/legacy/event/usenix05/tech/freenix/full_papers/eriksen/eriksen.pdf

Thanks @stefantalpalaru ! I'll close the issue now.
