### ISSUE TITLE
SyncManager: wall clock desync tolerance value can be 0

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#2218]
https://discord.com/channels/613988663034118151/771033358363918347/796990290371149844

```
WRN 2021-01-08 06:32:46.975+00:00 Local timer is broken or peer's status information is invalid topics="beacnde" tid=120491 file=sync_manager.nim:752 wall_clock_slot=271961 remote_head_slot=271962 local_head_slot=269254 peer=16U*mELUgu index=0 tolerance_value=0 peer_speed=2795.0 peer_score=200
```

notice that there is only 1 slot difference and the tolerance_value=0

In the sync manager code the default is one and not overriden:

https://github.com/status-im/nimbus-eth2/blob/91741326cc529f02817a1887180316a969b76998/beacon_chain/sync_manager.nim#L668-L680

https://github.com/status-im/nimbus-eth2/blob/f06e6d46a274699e006e50c869d78b2ff2b53498/beacon_chain/nimbus_beacon_node.nim#L718-L721

**Comment by arnetheduck** [comment]
https://github.com/ethereum/eth2.0-specs/blob/v1.0.0/specs/phase0/p2p-interface.md#configuration - generally we allow for 500ms (`MAXIMUM_GOSSIP_CLOCK_DISPARITY`) of clock disparity between nodes - should probably use the same tolerance here (ie not a full slot, but a slot offset by 500ms)

**Comment by mratsim** [comment]
Note: the original problem was solved (https://discord.com/channels/613988663034118151/771033358363918347/797045675300880415). It was due to clock syncing issues https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service-ubuntu.

That said I'm not too sure why the default 1 became 0 in the logs.

**Comment by arnetheduck** [comment]
tolerance check was removed in 5592c7c674bd7da5e93313726abc465a45e7e8b2
