### ISSUE TITLE
Nimbus 1.0.5 still reports as 1.0.4 (version.nim not up-to-date?)

### ISSUE THREAD

**Issue by ZaneCEO** [status-im/nimbus-eth2#2222]
As per title, `nimbus --version` reports `Nimbus beacon node v1.0.4-7d972282-stateofus`. I think this is due to [a missing update to version.nim](https://github.com/status-im/nimbus-eth2/commits/f06e6d46a274699e006e50c869d78b2ff2b53498/beacon_chain/version.nim)

**To Reproduce**

````
        cd $HOME
        git clone https://github.com/status-im/nimbus-eth2.git
        cd nimbus-eth2
        make -j4 beacon_node
        mv $HOME/nimbus-eth2/build/beacon_node /usr/local/bin/nimbus
        nimbus --version
````

**Comment by tersec** [comment]
The 1.0.5 release has been rescinded, partly due to this.
