### ISSUE TITLE
Remotely disconnected peer does not seem to get handled

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth2#775]
There is logic available that adds `onPeerClosed` callbacks to `lifeFuture` of a `Peer` (or rather `PeerInfo`).
e.g. here: https://github.com/status-im/nim-beacon-chain/blob/devel/beacon_chain/libp2p_backend.nim#L176
and here: https://github.com/status-im/nim-beacon-chain/blob/devel/beacon_chain/peer_pool.nim#L257

However, there seems to be nothing available to trigger these in case of a remote disconnect.
Actually, currently also not in the case in case the node does the disconnect, but that gets fixed here: https://github.com/status-im/nim-beacon-chain/pull/774 

I also noticed that the `node.switch.connections.len` in `DiscoveryLoop` remains the same in those cases, which makes me think that this is also missing in libp2p. Does [cleanupConn](https://github.com/status-im/nim-libp2p/blob/master/libp2p/switch.nim#L135) get called in those cases for example?

**Comment by arnetheduck** [comment]
this has been rewritten extensively since - peer tracking is being improved in libp2p in general
