### ISSUE TITLE
Fork Choice: EF test vectors integration

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#777]
Splitting from https://github.com/status-im/nim-beacon-chain/issues/719

Target: March 2020 if released upstream
The original issue will only track our own implementation and own independent sanity checks.

**Comment by mratsim** [comment]
Apr 1 Status: no test vectors from upstream yet so delayed

**Comment by mratsim** [comment]
Still WIP upstream https://github.com/ethereum/eth2.0-spec-tests/issues/17
But we have a much better Fork choice test suite now from #865

**Comment by mratsim** [comment]
Upstream fork choice tests were introduced in https://github.com/ethereum/eth2.0-specs/pull/2202

**Comment by tersec** [comment]
https://github.com/ethereum/consensus-spec-tests/tree/v1.1.0-beta.3/tests/mainnet/phase0/fork_choice
https://github.com/ethereum/consensus-spec-tests/tree/v1.1.0-beta.3/tests/mainnet/altair/fork_choice

**Comment by tersec** [comment]
Merge has these too: https://github.com/ethereum/consensus-spec-tests/tree/v1.1.0-beta.3/tests/mainnet/merge/fork_choice
