### ISSUE TITLE
Publish a Coding Style Guide

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#854]
With the increased adoption of Nim in Status, members of the Core Status team and the Vac team can benefit from a guide outlining various best practices and things to watch out for when working with Nim. Furthermore, the release of Nim 1.2 brings some new code safety features that we would like to enforce stronger throughout our codebases. To facilitate both of these goals, we should publish a "Status Nim Code Style Guide" which suggests coding practices and provides the rationale for them.

**Comment by arnetheduck** [comment]
https://status-im.github.io/nim-style-guide/
