### ISSUE TITLE
Distinct type: BlockRoot and StateRoot

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#960]
When reading specs and refactoring, everything is a `root` which can easily lead to confusion.

`BlockRoot` and `StateRoot` should be made distinct types of `Eth2Digest`.

**Comment by arnetheduck** [comment]
there's reason to make `Eth2Digest` distinct also - in particular, `MDigest` unfortunately prints hex in uppercase which breaks with custom in eth2 - silly and annoying but perhaps worth the occasional cast here and there

**Comment by arnetheduck** [comment]
For this to make sense, one would also have to specialize `hash_tree_root` to produce such roots when hashing blocks and states respectively - is this something worth pursuing still?

**Comment by tersec** [comment]
I can't think of bugs we've encountered which it'd have prevented. I'm pretty neutral on this if someone else feels so inclined, but don't think it's worth much effort.

**Comment by mratsim** [comment]
We didn't have bugs but i did spend time to make sure I wasn't using state_root instead of block_root when refactoring the ChainDAG.

Tagging low priority now, I do expect this is worthwhile before bigger refactorings in the future (like merging forkchoice with ChainDAG).

**Comment by arnetheduck** [comment]
Closing as this is unlikely to reach the effort vs utility threshold, per discussion above
