### ISSUE TITLE
Attestations DB and Attestations Aggregation inefficient data structure

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#981]
Mentioned in the code in a couple places, we have currently quadratic complexity when handling attestations in a couple of places:

https://github.com/status-im/nim-beacon-chain/blob/621c2e38a6f073c1c4bb9cf2e6b430796490a6ef/beacon_chain/validator_duties.nim#L255-L280

https://github.com/status-im/nim-beacon-chain/blob/621c2e38a6f073c1c4bb9cf2e6b430796490a6ef/beacon_chain/validator_duties.nim#L326-L353

https://github.com/status-im/nim-beacon-chain/blob/621c2e38a6f073c1c4bb9cf2e6b430796490a6ef/beacon_chain/attestation_pool.nim#L192-L250

https://github.com/status-im/nim-beacon-chain/blob/621c2e38a6f073c1c4bb9cf2e6b430796490a6ef/beacon_chain/attestation_pool.nim#L278-L310

https://github.com/status-im/nim-beacon-chain/blob/621c2e38a6f073c1c4bb9cf2e6b430796490a6ef/beacon_chain/attestation_pool.nim#L312-L371

The last link mentions in particular
```
       # TODO We need to select a set of attestations that maximise profit by 
       #      adding the largest combined attestation set that we can find - this 
       #      unfortunately looks an awful lot like 
       #      https://en.wikipedia.org/wiki/Set_packing - here we just iterate 
       #      and naively add as much as possible in one go, by we could also 
       #      add the same attestation data twice, as long as there's at least 
       #      one new attestation in there 
```

A potential way to solve that is to store attestations in a disjoint-set / union-find data structure. https://en.wikipedia.org/wiki/Disjoint-set_data_structure

**Comment by arnetheduck** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/2495
