### ISSUE TITLE
Benchmarks: display throughput

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#992]
The current blocksim benchmark is in time but what we are really interested in is not the time it takes to process a block (~latency) but how many blocks per second we can process (throughput).

**Comment by arnetheduck** [comment]
The two are isomorphic and give this is dev tooling it feels kind of arbitrary which one is given - the time it takes for example determines whether we need to be worried about dropped connections or not etc which is a developer concern - user logs already show throughput, so I'd leave this as-is
