### ISSUE TITLE
Kickstart the development of our RESTful API

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#993]
Success criteria for the initial work:

* [ ] We have a minimal HTTP 1.1 server that can take the place of the JSON-RPC API and our metrics server.

* [ ] The initial implementation is allowed to forgo implementing some parts of the HTTP spec as long as it's compatible with some key tools and programming APIs (curl, Postman, Python's requests module, etc)

* [ ] It support some key features of HTTP 1.1 such as persistent connections, chunked encoding and TLS 1.2 (through BearSSL).

* [ ] The API is built in layers and enough control is exposed over important aspects of RESTful services such as caching

* [ ] The design is completely compatible with fuzzing

* [ ] We have recruited a suitable external contributor under the bounty program to continue to work in the coming months in order to make the server more spec compliant

**Comment by oskarth** [comment]
What's the current state of this in terms of priority etc? Asking because it'd be relevant for Waku API.

**Comment by oskarth** [comment]
I don't know what I'm talking about here really, but has using the Nginx Module API been considered?

A quick search shows stuff like https://github.com/ba0f3/ngxcmod.nim and https://github.com/Taymindis/nginx-link-function

**Comment by arnetheduck** [comment]
This is implemented in https://github.com/status-im/nim-presto/
